#!/bin/bash
echo
echo cd ~/repos/
echo
echo get link for the CODE on website
echo
echo git clone https://github.com/CODE_LINK_HERE
echo
echo Examples:
echo
echo " ---> git clone https://github.com/dennyrgood/place-objects"
echo
echo " ---> git clone --branch copilot/build-visionos-app-apple-vision-pro https://github.com/dennyrgood/place-objects"
echo

