#!/bin/zsh
HOST=${1:-imagebeast}

curl -s http://$HOST:8188/object_info | python3 -c "
import json,sys
data = json.load(sys.stdin)
for name in sorted(data.keys()):
    cat = data[name].get('category','')
    print(f'[{cat}]  {name}')
"
