import os
import json
import time
from pathlib import Path
from datetime import datetime
from flask import Flask, jsonify, make_response, send_file, send_from_directory
# Import your existing config
# Make sure config.py has STATUS_DIR and CHECKER_HOST defined
try:
    import config
except ImportError:
    print("[ERROR] config.py not found. Ensure it is in the same directory.")
    exit(1)
app = Flask(__name__)
# The path to the specific JSON file generated by Phase 1
STATUS_FILE = os.path.join(config.STATUS_DIR, "server_status_all.json")
WEB_DIR = os.path.join(config.ONEDRIVE_PATH, "_sync_monitor", "Web")
def get_file_age(filepath):
    """Returns the age of the file in seconds."""
    try:
        mtime = os.path.getmtime(filepath)
        return int(time.time() - mtime)
    except OSError:
        return None
def add_custom_headers(data, status_code=200):
    response = make_response(jsonify(data), status_code)

    # This is the "Magic Line" that fixes the HTML connection
    response.headers['Access-Control-Allow-Origin'] = '*'

    response.headers['X-Checker-Host'] = getattr(config, 'CHECKER_HOST', 'unknown')
    age = get_file_age(STATUS_FILE)
    response.headers['X-Data-Age'] = str(age) if age is not None else "unknown"
    return response
@app.route('/')
def index():
    return send_file(os.path.join(WEB_DIR, 'index.html'))

@app.route('/<path:path>')
def static_files(path):
    return send_from_directory(WEB_DIR, path)

@app.route('/health', methods=['GET'])
def health_check():
    """Simple endpoint for Cloudflare health monitors."""
    return add_custom_headers({
        "status": "ok",
        "checker_host": getattr(config, 'CHECKER_HOST', 'unknown'),
        "timestamp": datetime.now().isoformat()
    })
@app.route('/api/status', methods=['GET'])
def get_status():
    """Reads and returns the master status JSON."""
    if not os.path.exists(STATUS_FILE):
        return add_custom_headers({"error": "Status file not found on host"}, 503)
    try:
        with open(STATUS_FILE, 'r') as f:
            data = json.load(f)
        return add_custom_headers(data)
    except (json.JSONDecodeError, IOError) as e:
        return add_custom_headers({"error": f"Failed to read status data: {str(e)}"}, 503)
if __name__ == '__main__':
    # Running on port 5010 as per Phase 2 requirements
    print(f"Starting Fleet API for {getattr(config, 'CHECKER_HOST', 'unknown')}...")
    print(f"Serving data from: {STATUS_FILE}")
    app.run(host='0.0.0.0', port=5010, debug=False)