#!/usr/bin/env python3
"""
comfy_fleet.py
ComfyUI Fleet Analysis Tool

Reads reports generated by the PowerShell scripts on each machine and produces:
  - Cross-machine model gap analysis
  - 2026 workflow priority lists
  - VRAM-aware model recommendations per machine
  - Custom node comparison across fleet
  - Robocopy sync scripts (Windows .bat)
  - HTML summary report
  - Drift detection vs previous run
  - Travel readiness score
  - Prioritized next-actions list

Usage:
    python3 comfy_fleet.py
    python3 comfy_fleet.py --config /path/to/fleet_config.json
    python3 comfy_fleet.py --year 2025   # override workflow year filter
"""

import json
import csv
import os
import re
import sys
import shutil
import argparse
from datetime import datetime
from pathlib import Path
from collections import defaultdict


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------

def find_latest(reports_dir: Path, hostname: str, pattern: str) -> Path | None:
    """Find the most recent file matching hostname + pattern glob."""
    matches = sorted(reports_dir.glob(f"{hostname}-{pattern}"))
    return matches[-1] if matches else None


def load_machine_files(reports_dir: Path, hostname: str) -> dict:
    """Load all report files for a machine, returning the latest of each type."""
    files = {}
    patterns = {
        "models":   "Models-*.csv",
        "full_map": "WorkflowMap-*-full_map.csv",
        "usage":    "WorkflowMap-*-model_usage.csv",
        "unused":   "WorkflowMap-*-unused_models.csv",
        "missing":  "WorkflowMap-*-missing_models.csv",
        "nodes":    "CustomNodes-*.txt",
    }
    for key, pattern in patterns.items():
        f = find_latest(reports_dir, hostname, pattern)
        if f:
            files[key] = f
        else:
            print(f"  WARNING: No {key} file found for {hostname}")
    return files


def load_csv(path: Path) -> list[dict]:
    with open(path, encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def load_nodes(path: Path) -> set[str]:
    nodes = set()
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line and line[0].isdigit():
                name = line.split(". ", 1)[-1].strip().lower()
                if name not in (".disabled", "__pycache__"):
                    nodes.add(name)
    return nodes


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_all_machines(config: dict) -> dict:
    reports_dir = Path(config["reports_dir"])
    data = {}

    for hostname, machine_cfg in config["machines"].items():
        print(f"Loading {hostname}...")
        files = load_machine_files(reports_dir, hostname)
        if not files:
            print(f"  SKIP: no files found for {hostname}")
            continue

        entry = {
            "config":   machine_cfg,
            "files":    files,
            "models":   {},   # filename.lower() -> row
            "nodes":    set(),
            "full_map": [],
        }

        if "models" in files:
            rows = load_csv(files["models"])
            for r in rows:
                entry["models"][r["filename"].lower()] = r
            print(f"  {len(entry['models'])} models")

        if "nodes" in files:
            entry["nodes"] = load_nodes(files["nodes"])
            print(f"  {len(entry['nodes'])} custom nodes")

        if "full_map" in files:
            entry["full_map"] = load_csv(files["full_map"])
            print(f"  {len(entry['full_map'])} full_map rows")

        if "unused" in files:
            entry["unused"] = load_csv(files["unused"])

        if "missing" in files:
            entry["missing_csv"] = load_csv(files["missing"])

        data[hostname] = entry

    return data


# ---------------------------------------------------------------------------
# Model gap analysis
# ---------------------------------------------------------------------------

def build_model_universe(data: dict) -> dict:
    """Build unified model info from all machines."""
    universe = {}
    for hostname, machine in data.items():
        for fn_lower, row in machine["models"].items():
            if fn_lower not in universe:
                universe[fn_lower] = {
                    "filename": row["filename"],
                    "category": row.get("category", ""),
                    "size_gb":  float(row.get("size_gb", 0)),
                    "on":       set(),
                    "paths":    {},
                }
            universe[fn_lower]["on"].add(hostname)
            universe[fn_lower]["paths"][hostname] = row.get("full_path", "")
    return universe


def build_workflow_model_data(data: dict, year_filter: str) -> dict:
    """
    For each model, collect which workflows reference it (filtered by year)
    and whether it's on disk on each machine.
    """
    model_wf = defaultdict(lambda: {
        "workflows": defaultdict(set),  # machine -> set of workflow names
        "on":        set(),
        "display":   "",
        "ref":       "",
    })

    for hostname, machine in data.items():
        for row in machine["full_map"]:
            if not row.get("workflow_modified", "").startswith(year_filter):
                continue
            fn   = row["model_filename"]
            ref  = row["model_ref"]
            ref_base = ref.replace("\\", "/").split("/")[-1]
            key  = fn.lower() if fn != "(not found on disk)" else ref_base.lower()

            wf_short = row["workflow_file"].split("\\")[-1]
            model_wf[key]["workflows"][hostname].add(wf_short)

            if fn != "(not found on disk)":
                model_wf[key]["on"].add(hostname)
            if not model_wf[key]["display"]:
                model_wf[key]["display"] = fn if fn != "(not found on disk)" else ref_base
            if not model_wf[key]["ref"]:
                model_wf[key]["ref"] = ref

    # Also mark presence from models CSV
    for hostname, machine in data.items():
        for key in model_wf:
            if key in machine["models"]:
                model_wf[key]["on"].add(hostname)

    return dict(model_wf)


def max_wf_count(model_entry: dict) -> int:
    return max((len(wfs) for wfs in model_entry["workflows"].values()), default=0)


# ---------------------------------------------------------------------------
# Drift detection
# ---------------------------------------------------------------------------

def load_history(history_dir: Path) -> dict | None:
    history_dir.mkdir(parents=True, exist_ok=True)
    files = sorted(history_dir.glob("snapshot-*.json"))
    if not files:
        return None
    with open(files[-1]) as f:
        return json.load(f)


def save_snapshot(history_dir: Path, data: dict, timestamp: str):
    history_dir.mkdir(parents=True, exist_ok=True)
    snapshot = {
        "timestamp": timestamp,
        "machines": {}
    }
    for hostname, machine in data.items():
        snapshot["machines"][hostname] = {
            "model_count": len(machine["models"]),
            "node_count":  len(machine["nodes"]),
            "models":      sorted(machine["models"].keys()),
            "nodes":       sorted(machine["nodes"]),
        }
    out = history_dir / f"snapshot-{timestamp}.json"
    with open(out, "w") as f:
        json.dump(snapshot, f, indent=2)
    print(f"Snapshot saved: {out.name}")


def compute_drift(previous: dict | None, data: dict) -> dict:
    drift = {}
    if not previous:
        return drift

    for hostname, machine in data.items():
        if hostname not in previous.get("machines", {}):
            drift[hostname] = {"new_machine": True}
            continue

        prev = previous["machines"][hostname]
        curr_models = set(machine["models"].keys())
        prev_models = set(prev.get("models", []))
        curr_nodes  = machine["nodes"]
        prev_nodes  = set(prev.get("nodes", []))

        drift[hostname] = {
            "models_added":   sorted(curr_models - prev_models),
            "models_removed": sorted(prev_models - curr_models),
            "nodes_added":    sorted(curr_nodes  - prev_nodes),
            "nodes_removed":  sorted(prev_nodes  - curr_nodes),
            "prev_date":      previous.get("timestamp", "unknown"),
        }

    return drift


# ---------------------------------------------------------------------------
# Travel readiness score
# ---------------------------------------------------------------------------

def compute_readiness(data: dict, wf_model_data: dict, hostname: str, year_filter: str) -> dict:
    """What % of year_filter workflows can run on this machine."""
    machine = data.get(hostname)
    if not machine:
        return {}

    # Group workflow/model pairs by workflow
    wf_missing = defaultdict(set)
    wf_total   = set()

    for row in machine["full_map"]:
        if not row.get("workflow_modified", "").startswith(year_filter):
            continue
        wf = row["workflow_file"].split("\\")[-1]
        wf_total.add(wf)
        if row["on_disk"] == "NO":
            wf_missing[wf].add(row["model_ref"].replace("\\", "/").split("/")[-1])

    can_run    = len(wf_total) - len(wf_missing)
    total      = len(wf_total)
    pct        = round(can_run / total * 100) if total else 0

    return {
        "can_run":    can_run,
        "total":      total,
        "pct":        pct,
        "blocked_wf": dict(wf_missing),
    }


# ---------------------------------------------------------------------------
# Custom node analysis
# ---------------------------------------------------------------------------

def analyze_nodes(data: dict, wf_model_data: dict) -> dict:
    all_nodes   = set()
    for machine in data.values():
        all_nodes |= machine["nodes"]

    hostnames = list(data.keys())
    on_all    = {n for n in all_nodes if all(n in data[h]["nodes"] for h in hostnames)}
    matrix    = {}
    for node in sorted(all_nodes):
        matrix[node] = {h: node in data[h]["nodes"] for h in hostnames}

    missing_per_machine = {}
    for hostname in hostnames:
        missing_per_machine[hostname] = sorted(n for n in all_nodes if n not in data[hostname]["nodes"])

    return {
        "all_nodes":    sorted(all_nodes),
        "on_all":       sorted(on_all),
        "matrix":       matrix,
        "missing":      missing_per_machine,
        "hostnames":    hostnames,
    }


# ---------------------------------------------------------------------------
# Sync script generation
# ---------------------------------------------------------------------------

def generate_robocopy(models_to_copy: list, label: str, note: str,
                      src_root: str, dest_root: str) -> str:
    total_gb = sum(m["size_gb"] for m in models_to_copy)
    lines = [
        "@echo off",
        "REM " + "=" * 60,
        f"REM  {label}",
        f"REM  {note}",
        f"REM  {len(models_to_copy)} files  |  {total_gb:.2f} GB",
        "REM  Run this on IMAGEBEAST",
        f"REM  Source : {src_root}",
        f"REM  Dest   : {dest_root}",
        "REM  OneDrive syncs automatically to TravelBeast + ChatWorkhorse",
        "REM " + "=" * 60,
        "",
    ]

    by_subdir = defaultdict(list)
    for m in models_to_copy:
        rel   = m.get("relative_path", m["filename"])
        parts = rel.replace("\\\\", "\\").split("\\")
        subdir = "\\".join(parts[:-1])
        by_subdir[subdir].append(m)

    for subdir in sorted(by_subdir.keys()):
        entries  = by_subdir[subdir]
        src_dir  = f"{src_root}\\{subdir}" if subdir else src_root
        dst_dir  = f"{dest_root}\\{subdir}" if subdir else dest_root
        label_str = subdir if subdir else "(root)"
        lines.append(f"REM --- {label_str} ---")
        for m in sorted(entries, key=lambda x: x["filename"]):
            lines.append(f'REM   {m["size_gb"]:.2f} GB  [{m.get("wf_count",0)} wf]  {m["filename"]}')
        file_args = " ".join(f'"{m["filename"]}"' for m in entries)
        lines.append(f'robocopy "{src_dir}" "{dst_dir}" {file_args} /COPY:DAT /R:2 /W:5')
        lines.append("")

    lines += [
        "echo.",
        "echo " + "=" * 60,
        f"echo  {label}  -- COMPLETE",
        f"echo  {len(models_to_copy)} files  ({total_gb:.2f} GB)",
        "echo  OneDrive will sync to TravelBeast and ChatWorkhorse",
        "echo " + "=" * 60,
        "pause",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------

def generate_html(report_data: dict, timestamp: str, year_filter: str) -> str:
    machines   = report_data["machines"]
    drift      = report_data["drift"]
    readiness  = report_data["readiness"]
    nodes_data = report_data["nodes"]
    gaps       = report_data["gaps"]
    actions    = report_data["actions"]
    universe   = report_data["universe"]

    hostnames = list(machines.keys())

    def badge(val, good_text="YES", bad_text="NO"):
        color = "#2ecc71" if val else "#e74c3c"
        text  = good_text if val else bad_text
        return f'<span style="background:{color};color:white;padding:2px 8px;border-radius:4px;font-size:0.85em">{text}</span>'

    def pct_badge(pct):
        color = "#2ecc71" if pct >= 80 else "#f39c12" if pct >= 50 else "#e74c3c"
        return f'<span style="background:{color};color:white;padding:3px 10px;border-radius:4px;font-weight:bold">{pct}%</span>'

    rows_html = ""

    # --- ACTIONS ---
    actions_html = "<ul>"
    for a in actions:
        icon = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(a["priority"], "•")
        actions_html += f'<li>{icon} <strong>{a["title"]}</strong> — {a["detail"]}</li>'
    actions_html += "</ul>"

    # --- READINESS ---
    readiness_html = '<table><tr><th>Machine</th><th>VRAM</th><th>Workflows</th><th>Readiness</th></tr>'
    for h in hostnames:
        r    = readiness.get(h, {})
        vram = machines[h]["config"].get("vram_gb", "?")
        pct  = r.get("pct", 0)
        can  = r.get("can_run", 0)
        tot  = r.get("total", 0)
        readiness_html += f'<tr><td>{h}</td><td>{vram} GB</td><td>{can}/{tot}</td><td>{pct_badge(pct)}</td></tr>'
    readiness_html += "</table>"

    # --- DRIFT ---
    drift_html = ""
    for h, d in drift.items():
        if d.get("new_machine"):
            drift_html += f"<p><strong>{h}</strong>: new machine, no previous data</p>"
            continue
        added   = d.get("models_added", [])
        removed = d.get("models_removed", [])
        since   = d.get("prev_date", "?")
        drift_html += f"<h4>{h} (since {since})</h4><ul>"
        for m in added[:10]:
            drift_html += f'<li style="color:#2ecc71">+ {m}</li>'
        if len(added) > 10:
            drift_html += f"<li>... and {len(added)-10} more added</li>"
        for m in removed[:10]:
            drift_html += f'<li style="color:#e74c3c">- {m}</li>'
        if len(removed) > 10:
            drift_html += f"<li>... and {len(removed)-10} more removed</li>"
        if not added and not removed:
            drift_html += "<li>No changes</li>"
        drift_html += "</ul>"
    if not drift_html:
        drift_html = "<p>No previous run to compare against.</p>"

    # --- MODEL GAPS ---
    gaps_html = ""
    for gap in gaps:
        gaps_html += f'<h4>{gap["title"]}</h4>'
        if not gap["models"]:
            gaps_html += "<p>None — all good!</p>"
            continue
        total_gb = sum(m["size_gb"] for m in gap["models"])
        gaps_html += f'<p>{len(gap["models"])} files | {total_gb:.2f} GB total</p>'
        gaps_html += '<table><tr><th>Model</th><th>Category</th><th>Size</th><th>Workflows</th><th>VRAM</th></tr>'
        for m in gap["models"]:
            sz   = m["size_gb"]
            vram_color = "#2ecc71" if sz <= 8 else "#f39c12" if sz <= 12 else "#e74c3c"
            vram_label = "OK" if sz <= 8 else "MAYBE" if sz <= 12 else "BIG"
            gaps_html += (
                f'<tr><td>{m["filename"]}</td><td>{m.get("category","")}</td>'
                f'<td>{sz:.2f} GB</td><td>{m.get("wf_count",0)}</td>'
                f'<td><span style="background:{vram_color};color:white;padding:2px 6px;border-radius:3px">{vram_label}</span></td></tr>'
            )
        gaps_html += "</table>"

    # --- NODE MATRIX ---
    node_matrix_html = '<table><tr><th>Node</th>'
    for h in nodes_data["hostnames"]:
        node_matrix_html += f'<th>{h}</th>'
    node_matrix_html += '</tr>'
    for node in nodes_data["all_nodes"]:
        row_vals = nodes_data["matrix"][node]
        all_yes  = all(row_vals.values())
        bg = "" if all_yes else ' style="background:#fff8e1"'
        node_matrix_html += f'<tr{bg}><td>{node}</td>'
        for h in nodes_data["hostnames"]:
            present = row_vals.get(h, False)
            node_matrix_html += f'<td style="text-align:center">{badge(present)}</td>'
        node_matrix_html += '</tr>'
    node_matrix_html += "</table>"

    # --- UNUSED ON IMAGEBEAST ---
    unused_html = ""
    source = [h for h, m in machines.items() if m["config"].get("is_source")][0] if machines else ""
    if source and "unused" in machines.get(source, {}).get("files", {}):
        unused_rows = machines[source].get("unused", [])
        if unused_rows:
            total_waste = sum(float(r.get("size_gb", 0)) for r in unused_rows)
            unused_html = f'<p>{len(unused_rows)} unused models | {total_waste:.2f} GB reclaimable</p>'
            unused_html += '<table><tr><th>Model</th><th>Category</th><th>Size</th></tr>'
            for r in sorted(unused_rows, key=lambda x: float(x.get("size_gb", 0)), reverse=True):
                unused_html += f'<tr><td>{r.get("filename","")}</td><td>{r.get("category","")}</td><td>{float(r.get("size_gb",0)):.2f} GB</td></tr>'
            unused_html += "</table>"

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>ComfyUI Fleet Report — {timestamp}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         margin: 0; padding: 20px; background: #f5f5f5; color: #333; }}
  h1   {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
  h2   {{ color: #2c3e50; margin-top: 40px; border-left: 4px solid #3498db; padding-left: 12px; }}
  h3   {{ color: #555; }}
  h4   {{ color: #666; margin-bottom: 4px; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; background: white;
           box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-radius: 6px; overflow: hidden; }}
  th   {{ background: #2c3e50; color: white; padding: 10px 12px; text-align: left; }}
  td   {{ padding: 8px 12px; border-bottom: 1px solid #eee; font-size: 0.9em; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: #f9f9f9; }}
  .card {{ background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px;
           box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 30px; }}
  .summary-card {{ background: white; border-radius: 8px; padding: 16px; text-align: center;
                   box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  .summary-card .num {{ font-size: 2em; font-weight: bold; color: #3498db; }}
  .summary-card .lbl {{ font-size: 0.85em; color: #888; margin-top: 4px; }}
  ul li {{ margin-bottom: 6px; }}
  .timestamp {{ color: #888; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>ComfyUI Fleet Report</h1>
<p class="timestamp">Generated: {timestamp} &nbsp;|&nbsp; Year filter: {year_filter}</p>

<div class="summary-grid">
  <div class="summary-card">
    <div class="num">{len(hostnames)}</div>
    <div class="lbl">Machines</div>
  </div>
  <div class="summary-card">
    <div class="num">{sum(len(m["models"]) for m in machines.values())}</div>
    <div class="lbl">Total Models (across fleet)</div>
  </div>
  <div class="summary-card">
    <div class="num">{len(nodes_data["on_all"])}</div>
    <div class="lbl">Nodes on All Machines</div>
  </div>
</div>

<h2>Next Actions</h2>
<div class="card">{actions_html}</div>

<h2>Travel / Workflow Readiness ({year_filter})</h2>
<div class="card">{readiness_html}</div>

<h2>Model Drift (vs Last Run)</h2>
<div class="card">{drift_html}</div>

<h2>Model Gaps</h2>
<div class="card">{gaps_html}</div>

<h2>Custom Nodes — Fleet Matrix</h2>
<div class="card">{node_matrix_html}</div>

<h2>Unused Models on ImageBeast</h2>
<div class="card">{unused_html if unused_html else "<p>No unused models data available.</p>"}</div>

</body>
</html>"""
    return html



# ---------------------------------------------------------------------------
# Subdir mismatch analysis
# Find models that exist in both source and dest but at different relative paths
# ---------------------------------------------------------------------------

def analyze_subdir_mismatches(data: dict, config: dict) -> list:
    """Find models on both source and dest but in different subdirectories."""
    source_host = next(
        (h for h, m in config["machines"].items() if m.get("is_source")), None
    )
    if not source_host or source_host not in data:
        return []

    src_models = data[source_host]["models"]

    # Build lookup: filename.lower() -> normalized relative path (forward slashes)
    def norm(p):
        return p.replace("\\\\", "/").replace("\\", "/")

    src_relpath = {}
    for fn_lower, row in src_models.items():
        rel = row.get("relative_path", "")
        if rel:
            src_relpath[fn_lower] = norm(rel)

    mismatches = []
    seen = set()

    for hostname, machine in data.items():
        if hostname == source_host:
            continue
        if not config["machines"][hostname].get("models_bare"):
            continue

        for fn_lower, row in machine["models"].items():
            if fn_lower not in src_relpath:
                continue

            dest_rel_raw = row.get("relative_path", "")
            dest_rel = norm(dest_rel_raw)
            src_rel  = src_relpath[fn_lower]

            src_subdir  = "/".join(src_rel.split("/")[:-1])
            dest_subdir = "/".join(dest_rel.split("/")[:-1])

            if src_subdir.lower() != dest_subdir.lower():
                key = (fn_lower, src_rel.lower())
                if key not in seen:
                    seen.add(key)
                    mismatches.append({
                        "filename":    row["filename"],
                        "src_rel":     src_rel,
                        "dest_rel":    dest_rel,
                        "src_subdir":  src_subdir,
                        "dest_subdir": dest_subdir,
                        "hostname":    hostname,
                        "size_gb":     float(row.get("size_gb", 0)),
                    })

    return sorted(mismatches, key=lambda x: x["filename"].lower())


def generate_subdir_fix_bat(mismatches: list, src_root: str, dest_root: str) -> str:
    """Generate robocopy bat to move files to correct subdirs on Models_bare."""
    from collections import defaultdict
    lines = [
        "@echo off",
        "REM ============================================================",
        "REM  fix_subdir_structure.bat",
        "REM  Copies models in Models_bare to match ImageBeast subdir structure",
        "REM  Run this on IMAGEBEAST (or any machine with access to Models_bare)",
        f"REM  {len(mismatches)} files to relocate",
        "REM  SAFE: copies to new location only - delete old copies manually after verifying",
        "REM ============================================================",
        "",
        f"set DST={dest_root}",
        "",
    ]

    by_dest = defaultdict(list)
    for m in mismatches:
        by_dest[m["src_subdir"]].append(m)

    for dest_subdir, items in sorted(by_dest.items()):
        label = dest_subdir if dest_subdir else "(root)"
        lines.append(f"REM === Move to: {label} ===")
        for m in items:
            cur_win  = m["dest_subdir"].replace("/", "\\")
            tgt_win  = dest_subdir.replace("/", "\\")
            cur_dir  = f'%DST%\\{cur_win}' if cur_win else "%DST%"
            tgt_dir  = f'%DST%\\{tgt_win}' if tgt_win else "%DST%"
            lines.append(f'REM  {m["filename"]}  ({m["size_gb"]:.2f} GB)')
            lines.append(f'REM  FROM: {cur_dir}')
            lines.append(f'REM  TO  : {tgt_dir}')
            lines.append(f'robocopy "{cur_dir}" "{tgt_dir}" "{m["filename"]}" /COPY:DAT /R:2 /W:5')
            lines.append("")

    lines += [
        "echo.",
        "echo ============================================================",
        "echo  COPY COMPLETE",
        "echo  Verify files are in correct locations then delete old copies",
        "echo  Old files were NOT auto-deleted for safety",
        "echo ============================================================",
        "pause",
    ]
    return "\n".join(lines)



# ---------------------------------------------------------------------------
# Next actions builder
# ---------------------------------------------------------------------------

def build_actions(gaps: list, readiness: dict, drift: dict, nodes_data: dict) -> list:
    actions = []

    # Model sync actions - use gap's own priority field
    seen_scripts = set()
    for gap in gaps:
        if gap.get("is_sync") and gap["models"]:
            script = gap.get("script_name", "")
            if script in seen_scripts:
                continue
            seen_scripts.add(script)
            total_gb = sum(m["size_gb"] for m in gap["models"])
            priority = gap.get("priority", "medium")
            actions.append({
                "priority": priority,
                "title":    f"Run {script} on ImageBeast",
                "detail":   f"{len(gap['models'])} files, {total_gb:.2f} GB — copies to Models_bare for Travel + Chat",
            })

    # Readiness - only flag if low AND not explained by VRAM
    for h, r in readiness.items():
        pct = r.get("pct", 100)
        if pct < 60:
            actions.append({
                "priority": "medium",
                "title":    f"{h} readiness {pct}% — expected for lower-VRAM machine",
                "detail":   f"{r['can_run']}/{r['total']} workflows runnable. Blocked workflows require large models only suited for ImageBeast.",
            })

    # Missing nodes on TravelBeast
    travel_missing_nodes = nodes_data["missing"].get("TRAVELBEAST", [])
    high_value = [n for n in travel_missing_nodes if n in {
        "comfyui-qwenvl", "comfyui_ipadapter_plus", "was-ns",
        "vantage-dreamomni2", "comfyui_layerstyle", "comfyui-advancedliveportrait",
    }]
    if high_value:
        actions.append({
            "priority": "medium",
            "title":    "Install missing nodes on TravelBeast via ComfyUI Manager",
            "detail":   "Priority: " + ", ".join(high_value[:5]),
        })

    # Drift
    for h, d in drift.items():
        removed = d.get("models_removed", [])
        if removed:
            actions.append({
                "priority": "medium",
                "title":    f"{h}: {len(removed)} models removed since last run",
                "detail":   "Check: " + ", ".join(removed[:3]),
            })

    # Unused on ImageBeast
    actions.append({
        "priority": "low",
        "title":    "Review unused models on ImageBeast",
        "detail":   "Run cleanup to reclaim disk space (see Unused Models section)",
    })

    return actions


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="ComfyUI Fleet Analysis")
    parser.add_argument("--config", default=None, help="Path to fleet_config.json")
    parser.add_argument("--year",   default=None, help="Override workflow year filter")
    args = parser.parse_args()

    # Find config - check: explicit arg, CWD, then script directory
    if args.config:
        config_path = Path(args.config)
    else:
        cwd_config    = Path.cwd() / "fleet_config.json"
        script_config = Path(__file__).parent / "fleet_config.json"
        if cwd_config.exists():
            config_path = cwd_config
        elif script_config.exists():
            config_path = script_config
        else:
            print("ERROR: fleet_config.json not found.")
            print(f"  Looked in: {Path.cwd()} and {Path(__file__).parent}")
            print("  Pass --config /path/to/fleet_config.json or put fleet_config.json in current directory.")
            sys.exit(1)

    print(f"Loading config: {config_path}")
    config      = load_config(config_path)
    year_filter = args.year or config.get("workflow_year_filter", "2026")
    reports_dir = Path(config["reports_dir"])
    output_dir  = Path(config.get("output_dir", reports_dir / "fleet-output"))
    history_dir = Path(config.get("history_dir", reports_dir / "history"))
    timestamp   = datetime.now().strftime("%Y-%m-%d_%H%M")

    output_dir.mkdir(parents=True, exist_ok=True)
    history_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nReports dir : {reports_dir}")
    print(f"Output dir  : {output_dir}")
    print(f"Year filter : {year_filter}")
    print()

    # Load all machine data
    data = load_all_machines(config)
    if not data:
        print("ERROR: No machine data loaded. Check reports_dir and file patterns.")
        sys.exit(1)

    # Load history for drift detection
    previous = load_history(history_dir)
    drift    = compute_drift(previous, data)
    if previous:
        print(f"\nDrift comparison vs: {previous.get('timestamp','?')}")
    else:
        print("\nNo previous snapshot found — this run will be the baseline.")

    # Build universe
    universe = build_model_universe(data)
    wf_data  = build_workflow_model_data(data, year_filter)

    # Identify source machine
    source_host = next(
        (h for h, m in config["machines"].items() if m.get("is_source")),
        list(data.keys())[0]
    )
    src_models_root = config["sync"]["source_models_root"]
    dest_models_bare = config["sync"]["dest_models_bare"]

    # Readiness per machine
    readiness = {}
    for hostname in data:
        readiness[hostname] = compute_readiness(data, wf_data, hostname, year_filter)

    # Node analysis
    nodes_data = analyze_nodes(data, wf_data)

    # Model gaps
    vram_ok    = config["vram_thresholds"]["ok"]
    vram_maybe = config["vram_thresholds"]["maybe"]

    source_models = data[source_host]["models"] if source_host in data else {}

    # Group non-source machines by sync_group (explicit) or fall back to hostname
    # Machines in the same sync_group share a Models_bare destination
    gaps         = []
    sync_scripts = {}

    dest_groups = defaultdict(list)
    for hostname, machine in data.items():
        if hostname == source_host:
            continue
        group_key = config["machines"][hostname].get("sync_group", hostname)
        dest_groups[group_key].append(hostname)

    for dest_bare, hostnames_in_group in dest_groups.items():
        # Use the lowest VRAM in the group as the constraint
        vram = min(config["machines"][h].get("vram_gb", 99) for h in hostnames_in_group)
        group_label = " + ".join(hostnames_in_group)

        # Union of what ALL machines in this group are missing
        # (if they share Models_bare, missing set is identical, but union is safe)
        missing_keys = set()
        for hostname in hostnames_in_group:
            machine = data[hostname]
            for fn_lower in wf_data:
                if fn_lower not in machine["models"] and fn_lower in source_models:
                    if max_wf_count(wf_data[fn_lower]) >= 3:
                        missing_keys.add(fn_lower)

        missing = []
        for fn_lower in missing_keys:
            sz   = universe.get(fn_lower, {}).get("size_gb", 0)
            cat  = universe.get(fn_lower, {}).get("category", "")
            rel  = source_models[fn_lower].get("relative_path", fn_lower)
            missing.append({
                "filename":       source_models[fn_lower]["filename"],
                "filename_lower": fn_lower,
                "category":       cat,
                "size_gb":        sz,
                "wf_count":       max_wf_count(wf_data[fn_lower]),
                "relative_path":  rel,
            })
        missing.sort(key=lambda x: x["wf_count"], reverse=True)

        ok_models    = [m for m in missing if m["size_gb"] <= vram_ok]
        maybe_models = [m for m in missing if vram_ok < m["size_gb"] <= vram_maybe]
        big_models   = [m for m in missing if m["size_gb"] > vram_maybe]

        # Script name based on group (use first hostname if shared)
        script_tag = hostnames_in_group[0] if len(hostnames_in_group) == 1 else "ModelsBase"

        gaps.append({
            "title":       f"Copy to {group_label} — OK models (<= {vram_ok} GB, safe for {vram}GB VRAM)",
            "models":      ok_models,
            "script_name": f"sync_{script_tag}_MIN.bat",
            "is_sync":     True,
            "priority":    "high",
        })
        gaps.append({
            "title":       f"Copy to {group_label} — MAYBE models ({vram_ok}-{vram_maybe} GB, marginal for {vram}GB VRAM)",
            "models":      maybe_models,
            "script_name": f"sync_{script_tag}_MAYBE.bat",
            "is_sync":     True,
            "priority":    "medium",
        })
        gaps.append({
            "title":       f"Skip for {group_label} — BIG models (> {vram_maybe} GB, too large for {vram}GB VRAM)",
            "models":      big_models,
            "is_sync":     False,
            "priority":    "low",
        })

        if ok_models:
            script = generate_robocopy(
                ok_models,
                f"sync_{script_tag}_MIN  -- Safe for {vram}GB VRAM (<= {vram_ok}GB each)",
                f"Copies to Models_bare shared by: {group_label}",
                src_models_root, dest_models_bare
            )
            sync_scripts[f"sync_{script_tag}_MIN.bat"] = script

        if maybe_models:
            script = generate_robocopy(
                maybe_models,
                f"sync_{script_tag}_MAYBE  -- Marginal ({vram_ok}-{vram_maybe}GB each)",
                f"Run after MIN. Marginal for {vram}GB VRAM — test before travelling.",
                src_models_root, dest_models_bare
            )
            sync_scripts[f"sync_{script_tag}_MAYBE.bat"] = script

    # Subdir mismatch analysis
    subdir_mismatches = analyze_subdir_mismatches(data, config)

    # Build actions
    report_data = {
        "machines":         data,
        "drift":            drift,
        "readiness":        readiness,
        "nodes":            nodes_data,
        "gaps":             gaps,
        "universe":         universe,
        "actions":          [],
        "subdir_mismatches": subdir_mismatches,
    }
    report_data["actions"] = build_actions(gaps, readiness, drift, nodes_data)

    # --- Write outputs ---

    # Robocopy scripts
    for name, script in sync_scripts.items():
        out = output_dir / name
        out.write_text(script)
        print(f"Written: {out.name}")

    # Custom nodes text report
    nodes_lines = []
    nodes_lines.append("CUSTOM NODES FLEET COMPARISON")
    nodes_lines.append(f"Generated: {timestamp}")
    nodes_lines.append("=" * 68)
    nodes_lines.append(f"  {'Node':<45} " + "  ".join(f"[{h[:6]}]" for h in nodes_data["hostnames"]))
    nodes_lines.append("-" * 68)
    for node in nodes_data["all_nodes"]:
        row = nodes_data["matrix"][node]
        cols = "     ".join("Y" if row.get(h) else " " for h in nodes_data["hostnames"])
        nodes_lines.append(f"  {node:<45} {cols}")
    nodes_lines.append("")
    nodes_lines.append("ON ALL MACHINES: " + ", ".join(nodes_data["on_all"]))
    (output_dir / f"custom_nodes_{timestamp}.txt").write_text("\n".join(nodes_lines))
    print(f"Written: custom_nodes_{timestamp}.txt")

    # Subdir mismatch report
    if subdir_mismatches:
        mismatch_lines = [
            "SUBDIR MISMATCH REPORT",
            f"Generated: {timestamp}",
            "Models that exist on both ImageBeast and Models_bare but in different subdirectories.",
            "Fix: run fix_subdir_structure.bat to copy to correct location, then delete old.",
            "=" * 72,
            "",
        ]
        for m in subdir_mismatches:
            mismatch_lines.append(f"  {m['filename']}  ({m['size_gb']:.2f} GB)")
            mismatch_lines.append(f"    ImageBeast (correct): {m['src_rel']}")
            mismatch_lines.append(f"    Models_bare (current): {m['dest_rel']}")
            mismatch_lines.append("")
        mismatch_lines.append(f"Total: {len(subdir_mismatches)} mismatches")
        (output_dir / f"subdir_mismatches_{timestamp}.txt").write_text("\n".join(mismatch_lines))
        print(f"Written: subdir_mismatches_{timestamp}.txt")

        fix_bat = generate_subdir_fix_bat(subdir_mismatches, src_models_root, dest_models_bare)
        (output_dir / "fix_subdir_structure.bat").write_text(fix_bat)
        print(f"Written: fix_subdir_structure.bat  ({len(subdir_mismatches)} files to relocate)")
    else:
        print("Subdir structure: OK (no mismatches found)")

    # HTML report
    html = generate_html(report_data, timestamp, year_filter)
    html_path = output_dir / f"fleet_report_{timestamp}.html"
    html_path.write_text(html)
    print(f"Written: fleet_report_{timestamp}.html")

    # Text summary
    summary_lines = []
    summary_lines.append(f"ComfyUI Fleet Analysis  {timestamp}")
    summary_lines.append(f"Year filter: {year_filter}")
    summary_lines.append("=" * 60)
    summary_lines.append("")
    summary_lines.append("READINESS")
    summary_lines.append("-" * 60)
    for h, r in readiness.items():
        vram = config["machines"][h].get("vram_gb", "?")
        summary_lines.append(f"  {h:<16} {r.get('pct',0):>3}%  ({r.get('can_run',0)}/{r.get('total',0)} workflows)  {vram}GB VRAM")
    summary_lines.append("")
    summary_lines.append("NEXT ACTIONS")
    summary_lines.append("-" * 60)
    for a in report_data["actions"]:
        p = {"high": "!!!", "medium": " ! ", "low": "   "}.get(a["priority"], "   ")
        summary_lines.append(f"  [{p}]  {a['title']}")
        summary_lines.append(f"         {a['detail']}")
    (output_dir / f"summary_{timestamp}.txt").write_text("\n".join(summary_lines))
    print(f"Written: summary_{timestamp}.txt")

    # Save snapshot for next run's drift detection
    save_snapshot(history_dir, data, timestamp)

    # Print summary to console
    print()
    print("\n".join(summary_lines))
    print(f"\nAll outputs in: {output_dir}")


if __name__ == "__main__":
    main()
