#!/usr/bin/env python3
"""
comfy_fleet.py
ComfyUI Fleet Analysis Tool

Reads reports generated by the PowerShell scripts on each machine and produces:
  - Cross-machine model gap analysis
  - 2026 workflow priority lists
  - VRAM-aware model recommendations per machine
  - Custom node comparison across fleet
  - Robocopy sync scripts (Windows .bat)
  - HTML summary report
  - Drift detection vs previous run
  - Travel readiness score
  - Prioritized next-actions list

Usage:
    python3 comfy_fleet.py
    python3 comfy_fleet.py --config /path/to/fleet_config.json
    python3 comfy_fleet.py --year 2025   # override workflow year filter
"""

import json
import csv
import os
import re
import sys
import shutil
import argparse
from datetime import datetime
from pathlib import Path
from collections import defaultdict


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------

def find_latest(reports_dir: Path, hostname: str, pattern: str) -> Path | None:
    """Find the most recent file matching hostname + pattern glob."""
    matches = sorted(reports_dir.glob(f"{hostname}-{pattern}"))
    return matches[-1] if matches else None


def load_machine_files(reports_dir: Path, hostname: str) -> dict:
    """Load all report files for a machine, returning the latest of each type."""
    files = {}
    patterns = {
        "models":   "Models-*.csv",
        "full_map": "WorkflowMap-*-full_map.csv",
        "usage":    "WorkflowMap-*-model_usage.csv",
        "unused":   "WorkflowMap-*-unused_models.csv",
        "missing":  "WorkflowMap-*-missing_models.csv",
        "nodes":    "CustomNodes-*.txt",
    }
    for key, pattern in patterns.items():
        f = find_latest(reports_dir, hostname, pattern)
        if f:
            files[key] = f
        else:
            print(f"  WARNING: No {key} file found for {hostname}")
    return files


def load_csv(path: Path) -> list[dict]:
    with open(path, encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def load_nodes(path: Path) -> set[str]:
    nodes = set()
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line and line[0].isdigit():
                name = line.split(". ", 1)[-1].strip().lower()
                if name not in (".disabled", "__pycache__"):
                    nodes.add(name)
    return nodes


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_all_machines(config: dict) -> dict:
    reports_dir = Path(config["reports_dir"])
    data = {}

    for hostname, machine_cfg in config["machines"].items():
        print(f"Loading {hostname}...")
        files = load_machine_files(reports_dir, hostname)
        if not files:
            print(f"  SKIP: no files found for {hostname}")
            continue

        entry = {
            "config":   machine_cfg,
            "files":    files,
            "models":   {},   # filename.lower() -> row
            "nodes":    set(),
            "full_map": [],
        }

        if "models" in files:
            rows = load_csv(files["models"])
            for r in rows:
                entry["models"][r["filename"].lower()] = r
            print(f"  {len(entry['models'])} models")

        if "nodes" in files:
            entry["nodes"] = load_nodes(files["nodes"])
            print(f"  {len(entry['nodes'])} custom nodes")

        if "full_map" in files:
            entry["full_map"] = load_csv(files["full_map"])
            print(f"  {len(entry['full_map'])} full_map rows")

        if "unused" in files:
            entry["unused"] = load_csv(files["unused"])

        if "missing" in files:
            entry["missing_csv"] = load_csv(files["missing"])

        data[hostname] = entry

    return data


# ---------------------------------------------------------------------------
# Model gap analysis
# ---------------------------------------------------------------------------

def build_model_universe(data: dict) -> dict:
    """Build unified model info from all machines."""
    universe = {}
    for hostname, machine in data.items():
        for fn_lower, row in machine["models"].items():
            if fn_lower not in universe:
                universe[fn_lower] = {
                    "filename": row["filename"],
                    "category": row.get("category", ""),
                    "size_gb":  float(row.get("size_gb", 0)),
                    "on":       set(),
                    "paths":    {},
                }
            universe[fn_lower]["on"].add(hostname)
            universe[fn_lower]["paths"][hostname] = row.get("full_path", "")
    return universe


def build_workflow_model_data(data: dict, year_filter: str) -> dict:
    """
    For each model, collect which workflows reference it (filtered by year)
    and whether it's on disk on each machine.
    """
    model_wf = defaultdict(lambda: {
        "workflows": defaultdict(set),  # machine -> set of workflow names
        "on":        set(),
        "display":   "",
        "ref":       "",
    })

    for hostname, machine in data.items():
        for row in machine["full_map"]:
            if not row.get("workflow_modified", "").startswith(year_filter):
                continue
            fn   = row["model_filename"]
            ref  = row["model_ref"]
            ref_base = ref.replace("\\", "/").split("/")[-1]
            key  = fn.lower() if fn != "(not found on disk)" else ref_base.lower()

            wf_short = row["workflow_file"].split("\\")[-1]
            model_wf[key]["workflows"][hostname].add(wf_short)

            if fn != "(not found on disk)":
                model_wf[key]["on"].add(hostname)
            if not model_wf[key]["display"]:
                model_wf[key]["display"] = fn if fn != "(not found on disk)" else ref_base
            if not model_wf[key]["ref"]:
                model_wf[key]["ref"] = ref

    # Also mark presence from models CSV
    for hostname, machine in data.items():
        for key in model_wf:
            if key in machine["models"]:
                model_wf[key]["on"].add(hostname)

    return dict(model_wf)


def max_wf_count(model_entry: dict) -> int:
    return max((len(wfs) for wfs in model_entry["workflows"].values()), default=0)


# ---------------------------------------------------------------------------
# Drift detection
# ---------------------------------------------------------------------------

def load_history(history_dir: Path) -> dict | None:
    history_dir.mkdir(parents=True, exist_ok=True)
    files = sorted(history_dir.glob("snapshot-*.json"))
    if not files:
        return None
    with open(files[-1]) as f:
        return json.load(f)


def save_snapshot(history_dir: Path, data: dict, timestamp: str):
    history_dir.mkdir(parents=True, exist_ok=True)
    snapshot = {
        "timestamp": timestamp,
        "machines": {}
    }
    for hostname, machine in data.items():
        snapshot["machines"][hostname] = {
            "model_count": len(machine["models"]),
            "node_count":  len(machine["nodes"]),
            "models":      sorted(machine["models"].keys()),
            "nodes":       sorted(machine["nodes"]),
        }
    out = history_dir / f"snapshot-{timestamp}.json"
    with open(out, "w") as f:
        json.dump(snapshot, f, indent=2)
    print(f"Snapshot saved: {out.name}")


def compute_drift(previous: dict | None, data: dict) -> dict:
    drift = {}
    if not previous:
        return drift

    for hostname, machine in data.items():
        if hostname not in previous.get("machines", {}):
            drift[hostname] = {"new_machine": True}
            continue

        prev = previous["machines"][hostname]
        curr_models = set(machine["models"].keys())
        prev_models = set(prev.get("models", []))
        curr_nodes  = machine["nodes"]
        prev_nodes  = set(prev.get("nodes", []))

        drift[hostname] = {
            "models_added":   sorted(curr_models - prev_models),
            "models_removed": sorted(prev_models - curr_models),
            "nodes_added":    sorted(curr_nodes  - prev_nodes),
            "nodes_removed":  sorted(prev_nodes  - curr_nodes),
            "prev_date":      previous.get("timestamp", "unknown"),
        }

    return drift


# ---------------------------------------------------------------------------
# Travel readiness score
# ---------------------------------------------------------------------------

def compute_readiness(data: dict, wf_model_data: dict, hostname: str, year_filter: str) -> dict:
    """What % of year_filter workflows can run on this machine."""
    machine = data.get(hostname)
    if not machine:
        return {}

    # Group workflow/model pairs by workflow
    wf_missing = defaultdict(set)
    wf_total   = set()

    for row in machine["full_map"]:
        if not row.get("workflow_modified", "").startswith(year_filter):
            continue
        wf = row["workflow_file"].split("\\")[-1]
        wf_total.add(wf)
        if row["on_disk"] == "NO":
            wf_missing[wf].add(row["model_ref"].replace("\\", "/").split("/")[-1])

    can_run    = len(wf_total) - len(wf_missing)
    total      = len(wf_total)
    pct        = round(can_run / total * 100) if total else 0

    return {
        "can_run":    can_run,
        "total":      total,
        "pct":        pct,
        "blocked_wf": dict(wf_missing),
    }


# ---------------------------------------------------------------------------
# Custom node analysis
# ---------------------------------------------------------------------------

def analyze_nodes(data: dict, wf_model_data: dict) -> dict:
    all_nodes   = set()
    for machine in data.values():
        all_nodes |= machine["nodes"]

    hostnames = list(data.keys())
    on_all    = {n for n in all_nodes if all(n in data[h]["nodes"] for h in hostnames)}
    matrix    = {}
    for node in sorted(all_nodes):
        matrix[node] = {h: node in data[h]["nodes"] for h in hostnames}

    missing_per_machine = {}
    for hostname in hostnames:
        missing_per_machine[hostname] = sorted(n for n in all_nodes if n not in data[hostname]["nodes"])

    return {
        "all_nodes":    sorted(all_nodes),
        "on_all":       sorted(on_all),
        "matrix":       matrix,
        "missing":      missing_per_machine,
        "hostnames":    hostnames,
    }


# ---------------------------------------------------------------------------
# Sync script generation
# ---------------------------------------------------------------------------

def generate_robocopy(models_to_copy: list, label: str, note: str,
                      src_root: str, dest_root: str) -> str:
    total_gb = sum(m["size_gb"] for m in models_to_copy)
    lines = [
        "@echo off",
        "REM " + "=" * 60,
        f"REM  {label}",
        f"REM  {note}",
        f"REM  {len(models_to_copy)} files  |  {total_gb:.2f} GB",
        "REM  Run this on IMAGEBEAST",
        f"REM  Source : {src_root}",
        f"REM  Dest   : {dest_root}",
        "REM  OneDrive syncs automatically to TravelBeast + ChatWorkhorse",
        "REM " + "=" * 60,
        "",
    ]

    by_subdir = defaultdict(list)
    for m in models_to_copy:
        rel   = m.get("relative_path", m["filename"])
        parts = rel.replace("\\\\", "\\").split("\\")
        subdir = "\\".join(parts[:-1])
        by_subdir[subdir].append(m)

    for subdir in sorted(by_subdir.keys()):
        entries  = by_subdir[subdir]
        src_dir  = f"{src_root}\\{subdir}" if subdir else src_root
        dst_dir  = f"{dest_root}\\{subdir}" if subdir else dest_root
        label_str = subdir if subdir else "(root)"
        lines.append(f"REM --- {label_str} ---")
        for m in sorted(entries, key=lambda x: x["filename"]):
            lines.append(f'REM   {m["size_gb"]:.2f} GB  [{m.get("wf_count",0)} wf]  {m["filename"]}')
        file_args = " ".join(f'"{m["filename"]}"' for m in entries)
        lines.append(f'robocopy "{src_dir}" "{dst_dir}" {file_args} /COPY:DAT /R:2 /W:5')
        lines.append("")

    lines += [
        "echo.",
        "echo " + "=" * 60,
        f"echo  {label}  -- COMPLETE",
        f"echo  {len(models_to_copy)} files  ({total_gb:.2f} GB)",
        "echo  OneDrive will sync to TravelBeast and ChatWorkhorse",
        "echo " + "=" * 60,
        "pause",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------

def generate_html(report_data: dict, timestamp: str, year_filter: str) -> str:
    machines         = report_data["machines"]
    drift            = report_data["drift"]
    readiness        = report_data["readiness"]
    nodes_data       = report_data["nodes"]
    gaps             = report_data["gaps"]
    actions          = report_data["actions"]
    universe         = report_data["universe"]
    subdir_mismatches = report_data.get("subdir_mismatches", [])
    prime_coverage    = report_data.get("prime_coverage", {})
    prime_scan        = report_data.get("prime_scan", {})
    si_coverage       = report_data.get("si_coverage", {})
    si_scan           = report_data.get("si_scan", {})

    hostnames = list(machines.keys())

    def badge(val, good_text="YES", bad_text="NO"):
        color = "#2ecc71" if val else "#e74c3c"
        text  = good_text if val else bad_text
        return f'<span style="background:{color};color:white;padding:2px 8px;border-radius:4px;font-size:0.85em">{text}</span>'

    def pct_badge(pct):
        color = "#2ecc71" if pct >= 80 else "#f39c12" if pct >= 50 else "#e74c3c"
        return f'<span style="background:{color};color:white;padding:3px 10px;border-radius:4px;font-weight:bold">{pct}%</span>'

    rows_html = ""

    # --- ACTIONS ---
    actions_html = "<ul>"
    for a in actions:
        icon = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(a["priority"], "•")
        actions_html += f'<li>{icon} <strong>{a["title"]}</strong> — {a["detail"]}</li>'
    actions_html += "</ul>"

    # --- READINESS ---
    readiness_html = '<table><tr><th>Machine</th><th>VRAM</th><th>Workflows</th><th>Readiness</th></tr>'
    for h in hostnames:
        r    = readiness.get(h, {})
        vram = machines[h]["config"].get("vram_gb", "?")
        pct  = r.get("pct", 0)
        can  = r.get("can_run", 0)
        tot  = r.get("total", 0)
        readiness_html += f'<tr><td>{h}</td><td>{vram} GB</td><td>{can}/{tot}</td><td>{pct_badge(pct)}</td></tr>'
    readiness_html += "</table>"

    # --- DRIFT ---
    drift_html = ""
    for h, d in drift.items():
        if d.get("new_machine"):
            drift_html += f"<p><strong>{h}</strong>: new machine, no previous data</p>"
            continue
        added   = d.get("models_added", [])
        removed = d.get("models_removed", [])
        since   = d.get("prev_date", "?")
        drift_html += f"<h4>{h} (since {since})</h4><ul>"
        for m in added[:10]:
            drift_html += f'<li style="color:#2ecc71">+ {m}</li>'
        if len(added) > 10:
            drift_html += f"<li>... and {len(added)-10} more added</li>"
        for m in removed[:10]:
            drift_html += f'<li style="color:#e74c3c">- {m}</li>'
        if len(removed) > 10:
            drift_html += f"<li>... and {len(removed)-10} more removed</li>"
        if not added and not removed:
            drift_html += "<li>No changes</li>"
        drift_html += "</ul>"
    if not drift_html:
        drift_html = "<p>No previous run to compare against.</p>"

    # --- MODEL GAPS ---
    gaps_html = ""
    for gap in gaps:
        gaps_html += f'<h4>{gap["title"]}</h4>'
        if not gap["models"]:
            gaps_html += "<p>None — all good!</p>"
            continue
        total_gb = sum(m["size_gb"] for m in gap["models"])
        gaps_html += f'<p>{len(gap["models"])} files | {total_gb:.2f} GB total</p>'
        gaps_html += '<table><tr><th>Model</th><th>Category</th><th>Size</th><th>Workflows</th><th>VRAM</th></tr>'
        for m in gap["models"]:
            sz   = m["size_gb"]
            vram_color = "#2ecc71" if sz <= 8 else "#f39c12" if sz <= 12 else "#e74c3c"
            vram_label = "OK" if sz <= 8 else "MAYBE" if sz <= 12 else "BIG"
            gaps_html += (
                f'<tr><td>{m["filename"]}</td><td>{m.get("category","")}</td>'
                f'<td>{sz:.2f} GB</td><td>{m.get("wf_count",0)}</td>'
                f'<td><span style="background:{vram_color};color:white;padding:2px 6px;border-radius:3px">{vram_label}</span></td></tr>'
            )
        gaps_html += "</table>"

    # --- NODE MATRIX ---
    node_matrix_html = '<table><tr><th>Node</th>'
    for h in nodes_data["hostnames"]:
        node_matrix_html += f'<th>{h}</th>'
    node_matrix_html += '</tr>'
    for node in nodes_data["all_nodes"]:
        row_vals = nodes_data["matrix"][node]
        all_yes  = all(row_vals.values())
        bg = "" if all_yes else ' style="background:#fff8e1"'
        node_matrix_html += f'<tr{bg}><td>{node}</td>'
        for h in nodes_data["hostnames"]:
            present = row_vals.get(h, False)
            node_matrix_html += f'<td style="text-align:center">{badge(present)}</td>'
        node_matrix_html += '</tr>'
    node_matrix_html += "</table>"

    # --- SUBDIR MISMATCHES ---
    if subdir_mismatches:
        mismatch_html = f'<p>{len(subdir_mismatches)} files in wrong subdirectory — run <code>fix_subdir_structure.bat</code> to correct</p>'
        mismatch_html += '<table><tr><th>Model</th><th>Size</th><th>Current Path (Models_bare)</th><th>Correct Path (ImageBeast)</th></tr>'
        for m in subdir_mismatches:
            mismatch_html += (
                f'<tr>'
                f'<td>{m["filename"]}</td>'
                f'<td>{m["size_gb"]:.2f} GB</td>'
                f'<td style="color:#e74c3c;font-family:monospace;font-size:0.85em">{m["dest_rel"]}</td>'
                f'<td style="color:#2ecc71;font-family:monospace;font-size:0.85em">{m["src_rel"]}</td>'
                f'</tr>'
            )
        mismatch_html += '</table>'
    else:
        mismatch_html = '<p style="color:#2ecc71">All models are in the correct subdirectories.</p>'

    # --- CURRENT YEAR WORKFLOW COVERAGE ---
    if prime_coverage and prime_scan:
        json_c = prime_scan.get("json_count", 0)
        png_c  = prime_scan.get("png_count", 0)
        total  = prime_scan.get("prime_models", set())
        prime_html = f'<p>Scanned {json_c} JSON workflows + {png_c} PNGs &nbsp;|&nbsp; {len(total)} unique model references</p>'

        for hostname, cov in prime_coverage.items():
            confirmed = cov["confirmed"]
            missing   = cov["missing"]
            beyond    = cov["beyond"]
            prime_html += f'<h4>{hostname}</h4>'
            prime_html += f'<p>'
            prime_html += f'<span style="color:#2ecc71">&#10003; {len(confirmed)} prime models confirmed on disk</span> &nbsp;|&nbsp; '
            if missing:
                prime_html += f'<span style="color:#e74c3c">&#10007; {len(missing)} prime models MISSING</span> &nbsp;|&nbsp; '
            prime_html += f'<span style="color:#888">{len(beyond)} models beyond prime set</span>'
            prime_html += '</p>'
            if missing:
                prime_html += '<p><strong>Missing prime models (need to add):</strong></p>'
                prime_html += '<table><tr><th>Model</th></tr>'
                for m in missing:
                    prime_html += f'<tr style="background:#fff0f0"><td style="font-family:monospace">{m}</td></tr>'
                prime_html += '</table>'
            if beyond:
                total_beyond_gb = sum(b["size_gb"] for b in beyond)
                prime_html += f'<p><strong>Beyond prime set ({len(beyond)} models, {total_beyond_gb:.2f} GB):</strong></p>'
                prime_html += '<table><tr><th>Model</th><th>Category</th><th>Size</th></tr>'
                for b in beyond:
                    prime_html += f'<tr><td>{b["filename"]}</td><td>{b["category"]}</td><td>{b["size_gb"]:.2f} GB</td></tr>'
                prime_html += '</table>'
    else:
        prime_html = '<p>No prime_workflows_dir configured in fleet_config.json.</p>'

    # --- STARTING IMAGES COVERAGE ---
    if si_coverage and si_scan and si_scan.get("png_count", 0) > 0:
        png_c   = si_scan["png_count"]
        si_mods = si_scan.get("models", set())
        si_html = f'<p>Based on <strong>{png_c} PNGs</strong> in 000 Starting Images &nbsp;|&nbsp; <strong>{len(si_mods)} unique model references</strong></p>'

        for hostname, cov in si_coverage.items():
            confirmed = cov["confirmed"]
            missing   = cov["missing"]
            beyond    = cov["beyond"]
            total_beyond_gb = sum(b["size_gb"] for b in beyond)
            ok_color  = "#2ecc71" if not missing else "#e74c3c"
            si_html  += f'<h4>{hostname}</h4><p>'
            si_html  += f'<span style="background:{ok_color};color:white;padding:2px 8px;border-radius:4px">{"READY" if not missing else "NOT READY"}</span> &nbsp; '
            si_html  += f'<span style="color:#2ecc71">&#10003; {len(confirmed)} models present</span>'
            if missing:
                si_html += f' &nbsp;|&nbsp; <span style="color:#e74c3c">&#10007; {len(missing)} MISSING</span>'
            si_html  += f' &nbsp;|&nbsp; <span style="color:#888">{len(beyond)} beyond ({total_beyond_gb:.2f} GB)</span>'
            si_html  += '</p>'
            if missing:
                si_html += '<table><tr><th style="background:#e74c3c">Missing Model (must add to run these workflows)</th></tr>'
                for m in missing:
                    si_html += f'<tr style="background:#fff0f0"><td style="font-family:monospace">{m}</td></tr>'
                si_html += '</table>'
            if beyond:
                si_html += f'<details><summary style="cursor:pointer;color:#888">Beyond starting images set — {len(beyond)} models, {total_beyond_gb:.2f} GB (click to expand)</summary>'
                si_html += '<table><tr><th>Model</th><th>Category</th><th>Size</th></tr>'
                for b in beyond:
                    si_html += f'<tr><td>{b["filename"]}</td><td>{b["category"]}</td><td>{b["size_gb"]:.2f} GB</td></tr>'
                si_html += '</table></details>'

        # Per-workflow breakdown — use first non-source machine's confirmed set for status
        first_cov = next(iter(si_coverage.values()), {})
        confirmed_set = set(first_cov.get("confirmed", []))
        si_html += '<h4>Per-Workflow Status</h4>'
        si_html += '<table><tr><th>PNG</th><th>Models Referenced</th><th>Status</th></tr>'
        for wf in si_scan.get("workflows", []):
            wf_missing = [m for m in wf["models"] if m not in confirmed_set]
            status_color = "#2ecc71" if not wf_missing else "#e74c3c"
            status_text  = "Ready" if not wf_missing else f"Missing: {', '.join(wf_missing)}"
            si_html += f'<tr><td style="font-family:monospace;font-size:0.85em">{wf["name"]}</td>'
            si_html += f'<td style="font-size:0.8em">{", ".join(wf["models"])}</td>'
            si_html += f'<td style="color:{status_color}">{status_text}</td></tr>'
        si_html += '</table>'
    else:
        si_html = '<p>No Starting Images PNGs found. Add test output PNGs to the 000 Starting Images folder.</p>'

    # --- UNUSED ON IMAGEBEAST ---
    unused_html = ""
    source = [h for h, m in machines.items() if m["config"].get("is_source")][0] if machines else ""
    if source and "unused" in machines.get(source, {}).get("files", {}):
        unused_rows = machines[source].get("unused", [])
        if unused_rows:
            total_waste = sum(float(r.get("size_gb", 0)) for r in unused_rows)
            unused_html = f'<p>{len(unused_rows)} unused models | {total_waste:.2f} GB reclaimable</p>'
            unused_html += '<table><tr><th>Model</th><th>Category</th><th>Size</th></tr>'
            for r in sorted(unused_rows, key=lambda x: float(x.get("size_gb", 0)), reverse=True):
                unused_html += f'<tr><td>{r.get("filename","")}</td><td>{r.get("category","")}</td><td>{float(r.get("size_gb",0)):.2f} GB</td></tr>'
            unused_html += "</table>"

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>ComfyUI Fleet Report — {timestamp}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         margin: 0; padding: 20px; background: #f5f5f5; color: #333; }}
  h1   {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
  h2   {{ color: #2c3e50; margin-top: 40px; border-left: 4px solid #3498db; padding-left: 12px; }}
  h3   {{ color: #555; }}
  h4   {{ color: #666; margin-bottom: 4px; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; background: white;
           box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-radius: 6px; overflow: hidden; }}
  th   {{ background: #2c3e50; color: white; padding: 10px 12px; text-align: left; }}
  td   {{ padding: 8px 12px; border-bottom: 1px solid #eee; font-size: 0.9em; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: #f9f9f9; }}
  .card {{ background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px;
           box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 30px; }}
  .summary-card {{ background: white; border-radius: 8px; padding: 16px; text-align: center;
                   box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  .summary-card .num {{ font-size: 2em; font-weight: bold; color: #3498db; }}
  .summary-card .lbl {{ font-size: 0.85em; color: #888; margin-top: 4px; }}
  ul li {{ margin-bottom: 6px; }}
  .timestamp {{ color: #888; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>ComfyUI Fleet Report</h1>
<p class="timestamp">Generated: {timestamp} &nbsp;|&nbsp; Year filter: {year_filter}</p>

<div class="summary-grid">
  <div class="summary-card">
    <div class="num">{len(hostnames)}</div>
    <div class="lbl">Machines</div>
  </div>
  <div class="summary-card">
    <div class="num">{sum(len(m["models"]) for m in machines.values())}</div>
    <div class="lbl">Total Models (across fleet)</div>
  </div>
  <div class="summary-card">
    <div class="num">{len(nodes_data["on_all"])}</div>
    <div class="lbl">Nodes on All Machines</div>
  </div>
</div>

<h2>Next Actions</h2>
<div class="card">{actions_html}</div>

<h2>Travel / Workflow Readiness ({year_filter})</h2>
<div class="card">{readiness_html}</div>

<h2>Model Drift (vs Last Run)</h2>
<div class="card">{drift_html}</div>

<h2>Model Gaps</h2>
<div class="card">{gaps_html}</div>

<h2>Custom Nodes — Fleet Matrix</h2>
<div class="card">{node_matrix_html}</div>

<h2>Unused Models on ImageBeast</h2>
<div class="card">{unused_html if unused_html else "<p>No unused models data available.</p>"}</div>

<h2>Subdir Structure Mismatches</h2>
<div class="card">{mismatch_html}</div>

<h2>Starting Images — Travel Readiness</h2>
<div class="card">{si_html}</div>

<h2>Current Year Workflow Coverage ({year_filter})</h2>
<div class="card">{prime_html}</div>

</body>
</html>"""
    return html




# ---------------------------------------------------------------------------
# Prime workflow analysis
# Scan prime workflows dir + 000 Starting Images for model refs
# Report per-machine which models are beyond what prime workflows need
# ---------------------------------------------------------------------------

def scan_prime_workflows(config: dict) -> dict:
    """
    Scan prime workflows directory and 000 Starting Images for model references.
    Returns dict with:
      - prime_models: set of filename.lower() referenced
      - json_count: number of JSON workflows scanned
      - png_count:  number of PNGs scanned
      - missing_models: models referenced but not found in any machine
    """
    import json as _json
    import struct, zlib

    prime_dir   = config.get("prime_workflows_dir")
    starting_dir = config.get("prime_starting_images_dir")

    if not prime_dir:
        return {}

    prime_models = set()
    json_count   = 0
    png_count    = 0

    MODEL_KEYS = {"ckpt_name","unet_name","vae_name","clip_name","clip_name1",
                  "clip_name2","clip_name3","lora_name","control_net_name",
                  "model","upscale_model_name","ipadapter","pulid_file",
                  "gguf_name","model_name"}

    def extract_from_workflow_dict(wf):
        found = set()
        if not isinstance(wf, dict):
            return found
        nodes = wf.get("nodes", [])
        if not nodes and "prompt" in wf:
            # API format
            for node in wf["prompt"].values() if isinstance(wf["prompt"], dict) else []:
                if isinstance(node, dict) and "inputs" in node:
                    for k, v in node["inputs"].items():
                        if k in MODEL_KEYS and isinstance(v, str) and v:
                            found.add(v.split("/")[-1].split("\\")[-1].lower())
        for node in nodes:
            wv = node.get("widgets_values", [])
            if isinstance(wv, list):
                for v in wv:
                    if isinstance(v, str) and any(
                        v.lower().endswith(ext) for ext in
                        [".safetensors",".gguf",".pt",".pth",".bin"]
                    ):
                        found.add(v.split("/")[-1].split("\\")[-1].lower())
            inputs = node.get("inputs", {})
            if isinstance(inputs, dict):
                for k, v in inputs.items():
                    if k in MODEL_KEYS and isinstance(v, str) and v:
                        found.add(v.split("/")[-1].split("\\")[-1].lower())
        return found

    def extract_png_workflow(path):
        """Extract workflow JSON from PNG tEXt chunks."""
        try:
            with open(path, "rb") as f:
                sig = f.read(8)
                if sig != b"\x89PNG\r\n\x1a\n":
                    return None
                while True:
                    hdr = f.read(8)
                    if len(hdr) < 8:
                        break
                    length = struct.unpack(">I", hdr[:4])[0]
                    chunk_type = hdr[4:8].decode("latin1", errors="replace")
                    data = f.read(length)
                    f.read(4)  # crc
                    if chunk_type == "tEXt":
                        try:
                            null = data.index(b"\x00")
                            keyword = data[:null].decode("latin1")
                            value   = data[null+1:].decode("latin1", errors="replace")
                            if keyword.lower() in ("prompt", "workflow"):
                                return _json.loads(value)
                        except Exception:
                            pass
                    elif chunk_type == "IEND":
                        break
        except Exception:
            pass
        return None

    # Scan JSON workflows in prime dir (root only, not subdirs)
    prime_path = Path(prime_dir)
    if prime_path.exists():
        for jf in prime_path.glob("*.json"):
            try:
                wf = _json.loads(jf.read_text(encoding="utf-8", errors="replace"))
                refs = extract_from_workflow_dict(wf)
                prime_models |= refs
                json_count += 1
            except Exception:
                pass

    # Scan PNGs in 000 Starting Images
    if starting_dir:
        start_path = Path(starting_dir)
        if start_path.exists():
            for pf in start_path.glob("*.png"):
                wf = extract_png_workflow(pf)
                if wf:
                    refs = extract_from_workflow_dict(wf)
                    prime_models |= refs
                    png_count += 1

    return {
        "prime_models": prime_models,
        "json_count":   json_count,
        "png_count":    png_count,
    }


def analyze_prime_coverage(data: dict, prime_scan: dict, config: dict) -> dict:
    """
    For each machine, report:
    - which prime models are present (confirmed ready)
    - which prime models are missing (need to be added)
    - which machine models are beyond what prime workflows need
    """
    if not prime_scan:
        return {}

    prime_models = prime_scan.get("prime_models", set())
    results = {}

    for hostname, machine in data.items():
        machine_models = set(machine["models"].keys())

        confirmed   = sorted(prime_models & machine_models)
        missing     = sorted(prime_models - machine_models)
        beyond      = sorted(machine_models - prime_models)

        # Enrich beyond with size info
        beyond_rich = []
        for fn in beyond:
            row = machine["models"].get(fn, {})
            beyond_rich.append({
                "filename": row.get("filename", fn),
                "size_gb":  float(row.get("size_gb", 0)),
                "category": row.get("category", ""),
            })
        beyond_rich.sort(key=lambda x: x["size_gb"], reverse=True)

        results[hostname] = {
            "confirmed":    confirmed,
            "missing":      missing,
            "beyond":       beyond_rich,
            "prime_total":  len(prime_models),
        }

    return results

# ---------------------------------------------------------------------------
# Starting Images dedicated coverage report
# Scans ONLY the PNGs in 000 Starting Images — the curated travel set
# ---------------------------------------------------------------------------

def scan_starting_images(data: dict) -> dict:
    """
    Extract starting_images rows from each machine's full_map CSV.
    These are PNGs scanned from the 000 Starting Images folder,
    tagged source=starting_images by Get-WorkflowModelMap.ps1.
    Returns dict with models set and per-workflow breakdown.
    """
    all_models = set()
    workflows  = defaultdict(set)  # png_name -> set of model filenames

    for hostname, machine in data.items():
        for row in machine.get("full_map", []):
            if row.get("source", "").lower() != "starting_images":
                continue
            fn = row.get("model_filename", "")
            if fn and fn != "(not found on disk)":
                key = fn.lower()
                all_models.add(key)
                wf_name = row["workflow_file"].replace("\\", "/").split("/")[-1]
                workflows[wf_name].add(key)

    wf_list = [
        {"name": name, "models": sorted(models)}
        for name, models in sorted(workflows.items())
    ]

    return {
        "models":    all_models,
        "workflows": wf_list,
        "png_count": len(wf_list),
    }


def analyze_starting_images_coverage(data: dict, si_scan: dict) -> dict:
    """
    For each machine: which starting-image models are present / missing / beyond.
    """
    if not si_scan or not si_scan.get("models"):
        return {}

    si_models = si_scan["models"]
    results   = {}

    for hostname, machine in data.items():
        machine_models = set(machine["models"].keys())

        confirmed = sorted(si_models & machine_models)
        missing   = sorted(si_models - machine_models)
        beyond    = sorted(machine_models - si_models)

        beyond_rich = []
        for fn in beyond:
            row = machine["models"].get(fn, {})
            beyond_rich.append({
                "filename": row.get("filename", fn),
                "size_gb":  float(row.get("size_gb", 0)),
                "category": row.get("category", ""),
            })
        beyond_rich.sort(key=lambda x: x["size_gb"], reverse=True)

        results[hostname] = {
            "confirmed": confirmed,
            "missing":   missing,
            "beyond":    beyond_rich,
            "si_total":  len(si_models),
        }

    return results

# ---------------------------------------------------------------------------
# Subdir mismatch analysis
# Find models that exist in both source and dest but at different relative paths
# ---------------------------------------------------------------------------

def analyze_subdir_mismatches(data: dict, config: dict) -> list:
    """Find models on both source and dest but in different subdirectories."""
    source_host = next(
        (h for h, m in config["machines"].items() if m.get("is_source")), None
    )
    if not source_host or source_host not in data:
        return []

    src_models = data[source_host]["models"]

    # Build lookup: filename.lower() -> normalized relative path (forward slashes)
    def norm(p):
        return p.replace("\\\\", "/").replace("\\", "/")

    src_relpath = {}
    for fn_lower, row in src_models.items():
        rel = row.get("relative_path", "")
        if rel:
            src_relpath[fn_lower] = norm(rel)

    mismatches = []
    seen = set()

    for hostname, machine in data.items():
        if hostname == source_host:
            continue
        if not config["machines"][hostname].get("models_bare"):
            continue

        for fn_lower, row in machine["models"].items():
            if fn_lower not in src_relpath:
                continue

            dest_rel_raw = row.get("relative_path", "")
            dest_rel = norm(dest_rel_raw)
            src_rel  = src_relpath[fn_lower]

            src_subdir  = "/".join(src_rel.split("/")[:-1])
            dest_subdir = "/".join(dest_rel.split("/")[:-1])

            if src_subdir.lower() != dest_subdir.lower():
                key = (fn_lower, src_rel.lower())
                if key not in seen:
                    seen.add(key)
                    mismatches.append({
                        "filename":    row["filename"],
                        "src_rel":     src_rel,
                        "dest_rel":    dest_rel,
                        "src_subdir":  src_subdir,
                        "dest_subdir": dest_subdir,
                        "hostname":    hostname,
                        "size_gb":     float(row.get("size_gb", 0)),
                    })

    return sorted(mismatches, key=lambda x: x["filename"].lower())


def generate_subdir_fix_bat(mismatches: list, src_root: str, dest_root: str) -> str:
    """Generate robocopy bat to move files to correct subdirs on Models_bare."""
    from collections import defaultdict
    lines = [
        "@echo off",
        "REM ============================================================",
        "REM  fix_subdir_structure.bat",
        "REM  Copies models in Models_bare to match ImageBeast subdir structure",
        "REM  Run this on IMAGEBEAST (or any machine with access to Models_bare)",
        f"REM  {len(mismatches)} files to relocate",
        "REM  SAFE: copies to new location only - delete old copies manually after verifying",
        "REM ============================================================",
        "",
        f"set DST={dest_root}",
        "",
    ]

    by_dest = defaultdict(list)
    for m in mismatches:
        by_dest[m["src_subdir"]].append(m)

    for dest_subdir, items in sorted(by_dest.items()):
        label = dest_subdir if dest_subdir else "(root)"
        lines.append(f"REM === Move to: {label} ===")
        for m in items:
            cur_win  = m["dest_subdir"].replace("/", "\\")
            tgt_win  = dest_subdir.replace("/", "\\")
            cur_dir  = f'%DST%\\{cur_win}' if cur_win else "%DST%"
            tgt_dir  = f'%DST%\\{tgt_win}' if tgt_win else "%DST%"
            lines.append(f'REM  {m["filename"]}  ({m["size_gb"]:.2f} GB)')
            lines.append(f'REM  FROM: {cur_dir}')
            lines.append(f'REM  TO  : {tgt_dir}')
            lines.append(f'robocopy "{cur_dir}" "{tgt_dir}" "{m["filename"]}" /COPY:DAT /R:2 /W:5')
            lines.append("")

    lines += [
        "echo.",
        "echo ============================================================",
        "echo  COPY COMPLETE",
        "echo  Verify files are in correct locations then delete old copies",
        "echo  Old files were NOT auto-deleted for safety",
        "echo ============================================================",
        "pause",
    ]
    return "\n".join(lines)



# ---------------------------------------------------------------------------
# Next actions builder
# ---------------------------------------------------------------------------

def build_actions(gaps: list, readiness: dict, drift: dict, nodes_data: dict) -> list:
    actions = []

    # Model sync actions - use gap's own priority field
    seen_scripts = set()
    for gap in gaps:
        if gap.get("is_sync") and gap["models"]:
            script = gap.get("script_name", "")
            if script in seen_scripts:
                continue
            seen_scripts.add(script)
            total_gb = sum(m["size_gb"] for m in gap["models"])
            priority = gap.get("priority", "medium")
            actions.append({
                "priority": priority,
                "title":    f"Run {script} on ImageBeast",
                "detail":   f"{len(gap['models'])} files, {total_gb:.2f} GB — copies to Models_bare for Travel + Chat",
            })

    # Readiness - only flag if low AND not explained by VRAM
    for h, r in readiness.items():
        pct = r.get("pct", 100)
        if pct < 60:
            actions.append({
                "priority": "medium",
                "title":    f"{h} readiness {pct}% — expected for lower-VRAM machine",
                "detail":   f"{r['can_run']}/{r['total']} workflows runnable. Blocked workflows require large models only suited for ImageBeast.",
            })

    # Missing nodes on TravelBeast
    travel_missing_nodes = nodes_data["missing"].get("TRAVELBEAST", [])
    high_value = [n for n in travel_missing_nodes if n in {
        "comfyui-qwenvl", "comfyui_ipadapter_plus", "was-ns",
        "vantage-dreamomni2", "comfyui_layerstyle", "comfyui-advancedliveportrait",
    }]
    if high_value:
        actions.append({
            "priority": "medium",
            "title":    "Install missing nodes on TravelBeast via ComfyUI Manager",
            "detail":   "Priority: " + ", ".join(high_value[:5]),
        })

    # Drift
    for h, d in drift.items():
        removed = d.get("models_removed", [])
        if removed:
            actions.append({
                "priority": "medium",
                "title":    f"{h}: {len(removed)} models removed since last run",
                "detail":   "Check: " + ", ".join(removed[:3]),
            })

    # Unused on ImageBeast
    actions.append({
        "priority": "low",
        "title":    "Review unused models on ImageBeast",
        "detail":   "Run cleanup to reclaim disk space (see Unused Models section)",
    })

    return actions



# ---------------------------------------------------------------------------
# Fleet Explorer HTML generator
# ---------------------------------------------------------------------------

def generate_explorer_html(data: dict, timestamp: str, year_filter: str) -> str:
    """Generate interactive fleet explorer HTML with workflow/model cross-reference."""
    import json as _json

    hostnames  = list(data.keys())
    host_short = {h: h[:4] for h in hostnames}
    host_colors = {}
    palette = ['#3498db', '#e67e22', '#2ecc71', '#9b59b6']
    for i, h in enumerate(hostnames):
        host_colors[h] = palette[i % len(palette)]

    def js(obj):
        return _json.dumps(obj, separators=(',', ':'))

    # Build workflow and model data structures
    wf_data    = {}
    model_data = {}

    for hostname, machine in data.items():
        for row in machine.get("full_map", []):
            src     = row.get("source", "workflows")
            wf_file = row["workflow_file"].replace("\\", "/").split("/")[-1]
            wf_mod  = row.get("workflow_modified", "")[:10]
            wf_year = wf_mod[:4] if wf_mod else ""
            fn      = row.get("model_filename", "")
            ref     = row.get("model_ref", "").replace("\\", "/").split("/")[-1]
            on_disk = row.get("on_disk", "NO") == "YES"
            size_gb = float(row.get("model_size_gb", 0) or 0)
            cat     = row.get("model_category", "")

            mk = fn.lower() if fn and fn != "(not found on disk)" else ref.lower()
            if not mk:
                continue

            wk = f"{src}||{wf_file}"
            if wk not in wf_data:
                wf_data[wk] = {
                    "name": wf_file, "source": src,
                    "modified": wf_mod, "year": wf_year,
                    "models": set(),
                    "per_host": {h: {"present": 0, "missing": 0} for h in hostnames}
                }
            wf_data[wk]["models"].add(mk)
            if on_disk:
                wf_data[wk]["per_host"][hostname]["present"] += 1
            else:
                wf_data[wk]["per_host"][hostname]["missing"] += 1

            if mk not in model_data:
                model_data[mk] = {
                    "filename": fn if fn and fn != "(not found on disk)" else ref,
                    "size_gb": size_gb, "category": cat,
                    "on_hosts": {h: False for h in hostnames},
                    "workflows": set()
                }
            if on_disk:
                model_data[mk]["on_hosts"][hostname] = True
            if size_gb > model_data[mk]["size_gb"]:
                model_data[mk]["size_gb"] = size_gb
            model_data[mk]["workflows"].add(wf_file)

    # Convert sets to lists
    for wk in wf_data:
        wf_data[wk]["models"] = sorted(wf_data[wk]["models"])
    for mk in model_data:
        model_data[mk]["workflows"] = sorted(model_data[mk]["workflows"])

    def wf_list(source_filter=None, year=None):
        out = []
        for wk, wv in wf_data.items():
            if source_filter and wv["source"] not in source_filter:
                continue
            if year and wv["year"] != year:
                continue
            hs = {}
            for h in hostnames:
                ph = wv["per_host"].get(h, {"present": 0, "missing": 0})
                if ph["present"] == 0 and ph["missing"] == 0:
                    hs[h] = "N"
                elif ph["missing"] == 0:
                    hs[h] = "R"
                elif ph["present"] == 0:
                    hs[h] = "M"
                else:
                    hs[h] = "P"
            out.append({"key": wk, "name": wv["name"], "source": wv["source"],
                        "modified": wv["modified"], "year": wv["year"],
                        "models": wv["models"], "hs": hs})
        return sorted(out, key=lambda x: x["name"].lower())

    def model_list():
        out = []
        for mk, mv in model_data.items():
            out.append({"key": mk, "filename": mv["filename"], "size_gb": mv["size_gb"],
                        "category": mv["category"], "on_hosts": mv["on_hosts"],
                        "workflows": mv["workflows"], "wf_count": len(mv["workflows"])})
        return sorted(out, key=lambda x: x["filename"].lower())

    def pruning_models():
        yr_models = set()
        si_models = set()
        for wv in wf_data.values():
            if wv["source"] == "starting_images":
                si_models.update(wv["models"])
            if wv["year"] == year_filter and wv["source"] in ("workflows", "workflows-png"):
                yr_models.update(wv["models"])
        out = []
        for mk, mv in model_data.items():
            if not any(mv["on_hosts"].values()):
                continue
            if mk not in yr_models and mk not in si_models:
                out.append({"key": mk, "filename": mv["filename"], "size_gb": mv["size_gb"],
                            "category": mv["category"], "on_hosts": mv["on_hosts"],
                            "wf_count": len(mv["workflows"]),
                            "reason": f"Not in {year_filter} or Starting Images"})
        return sorted(out, key=lambda x: -x["size_gb"])

    def pruning_workflows():
        out = []
        for wk, wv in wf_data.items():
            if wv["source"] not in ("workflows", "workflows-png"):
                continue
            if not wv["year"] or wv["year"] >= str(int(year_filter) - 1):
                continue
            out.append({"key": wk, "name": wv["name"], "modified": wv["modified"],
                        "year": wv["year"], "model_count": len(wv["models"]),
                        "reason": f"Last modified {wv['modified'] or 'unknown'}"})
        return sorted(out, key=lambda x: x["modified"] or "")

    si_wfs    = wf_list(source_filter=["starting_images"])
    yr_wfs    = wf_list(source_filter=["workflows", "workflows-png"], year=year_filter)
    all_wfs   = wf_list(source_filter=["workflows", "workflows-png"])
    older_wfs = [w for w in all_wfs if w["year"] and w["year"] < year_filter]
    ml        = model_list()
    pm        = pruning_models()
    pw        = pruning_workflows()

    CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       background: #1a1a2e; color: #e0e0e0; height: 100vh; display: flex; flex-direction: column; }
.header { background: #16213e; padding: 12px 20px; display: flex; align-items: center;
          gap: 16px; border-bottom: 2px solid #0f3460; flex-shrink: 0; }
.header h1 { font-size: 1.1em; color: #4fc3f7; white-space: nowrap; }
.header .ts { font-size: 0.75em; color: #555; }
.search-box { flex: 1; max-width: 400px; padding: 6px 12px; border-radius: 20px;
              border: 1px solid #0f3460; background: #0f3460; color: #e0e0e0;
              font-size: 0.9em; outline: none; }
.search-box:focus { border-color: #4fc3f7; }
.mode-btn { padding: 6px 14px; border-radius: 20px; border: 1px solid #4fc3f7;
            background: transparent; color: #4fc3f7; cursor: pointer; font-size: 0.85em; }
.mode-btn.active, .mode-btn:hover { background: #4fc3f7; color: #1a1a2e; }
.clear-btn { padding: 6px 14px; border-radius: 20px; border: 1px solid #555;
             background: transparent; color: #888; cursor: pointer; font-size: 0.85em; }
.clear-btn:hover { border-color: #e74c3c; color: #e74c3c; }
.main { display: flex; flex: 1; overflow: hidden; gap: 1px; background: #0f3460; }
.panel { background: #1a1a2e; display: flex; flex-direction: column; overflow: hidden; }
.panel-workflows { flex: 1.4; }
.panel-models { flex: 1; }
.panel-header { background: #16213e; padding: 8px 12px; border-bottom: 1px solid #0f3460; flex-shrink: 0; }
.panel-header h2 { font-size: 0.85em; color: #4fc3f7; margin-bottom: 6px; }
.tabs { display: flex; gap: 4px; flex-wrap: wrap; }
.tab { padding: 4px 10px; border-radius: 12px; font-size: 0.78em; cursor: pointer;
       border: 1px solid #0f3460; color: #888; background: transparent; }
.tab.active { background: #0f3460; color: #e0e0e0; border-color: #4fc3f7; }
.tab:hover:not(.active) { border-color: #555; color: #bbb; }
.filters { padding: 6px 10px; background: #16213e; border-bottom: 1px solid #0f3460;
           display: flex; gap: 6px; flex-wrap: wrap; flex-shrink: 0; align-items: center; }
.filter-label { font-size: 0.75em; color: #666; }
.filter-chip { padding: 2px 8px; border-radius: 10px; font-size: 0.75em; cursor: pointer;
               border: 1px solid #0f3460; color: #888; background: transparent; }
.filter-chip.active { border-color: #4fc3f7; color: #4fc3f7; background: rgba(79,195,247,0.1); }
.list-container { flex: 1; overflow-y: auto; }
.list-container::-webkit-scrollbar { width: 4px; }
.list-container::-webkit-scrollbar-thumb { background: #0f3460; border-radius: 2px; }
.item { padding: 7px 12px; border-bottom: 1px solid #0d1b2e; cursor: pointer;
        display: flex; align-items: center; gap: 8px; }
.item:hover { background: #16213e; }
.item.selected { background: #0f3460; border-left: 3px solid #4fc3f7; padding-left: 9px; }
.item.dimmed { opacity: 0.2; }
.item.highlighted { background: rgba(79,195,247,0.07); }
.item-name { flex: 1; font-size: 0.82em; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.item-meta { font-size: 0.72em; color: #666; white-space: nowrap; }
.item-size { font-size: 0.72em; color: #888; white-space: nowrap; min-width: 42px; text-align: right; }
.host-dots { display: flex; gap: 3px; flex-shrink: 0; }
.dot { width: 8px; height: 8px; border-radius: 50%; }
.dot-R { background: #2ecc71; }
.dot-P { background: #f39c12; }
.dot-M { background: #e74c3c; }
.dot-N { background: #2a2a3e; }
.dot-on { background: #2ecc71; }
.dot-off { background: #e74c3c; }
.cat-tag { font-size: 0.68em; color: #666; background: #0d1b2e; padding: 1px 5px;
           border-radius: 4px; flex-shrink: 0; max-width: 90px; overflow: hidden;
           text-overflow: ellipsis; white-space: nowrap; }
.prune-badge { background: #c0392b; color: white; font-size: 0.68em;
               padding: 1px 5px; border-radius: 8px; flex-shrink: 0; white-space: nowrap; }
.prune-reason { font-size: 0.7em; color: #e74c3c; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.info-bar { background: #0f3460; padding: 6px 12px; font-size: 0.78em; color: #4fc3f7;
            flex-shrink: 0; min-height: 28px; border-top: 1px solid #16213e; }
.empty { padding: 30px; text-align: center; color: #555; font-size: 0.85em; }
"""

    JS = f"""
const HN = {js(hostnames)};
const HS = {js(host_short)};
const SI_WF    = {js(si_wfs)};
const YR_WF    = {js(yr_wfs)};
const OLDER_WF = {js(older_wfs)};
const ALL_WF   = {js(all_wfs)};
const MODELS  = {js(ml)};
const PRUNE_M  = {js(pm)};
const PRUNE_WF= {js(pw)};

let mode='normal', wfTab='si', modelTab='all';
let wfFilter='all', modelFilter='all';
let selectedWf=null, selectedModel=null, searchTerm='';
let highlightedModels=new Set(), highlightedWfs=new Set();
let showOnlyWf=false, showOnlyModel=false;

function setMode(m) {{
  mode=m;
  document.getElementById('normalBtn').classList.toggle('active',m==='normal');
  document.getElementById('pruneBtn').classList.toggle('active',m==='prune');
  ['tab-pwf','tab-mpm'].forEach(id=>{{
    const el=document.getElementById(id);
    if(el) el.style.display=m==='prune'?'':'none';
  }});
  if(m==='prune'){{switchTab('pwf');switchModelTab('prune');}}
  else{{switchTab('si');switchModelTab('all');}}
}}

function switchTab(t) {{
  wfTab=t;
  ['si','yr','older','all','pwf'].forEach(id=>{{
    const el=document.getElementById('tab-'+id);
    if(el) el.classList.toggle('active',id===t);
  }});
  clearSelection(); renderWf();
}}

function switchModelTab(t) {{
  modelTab=t;
  document.getElementById('tab-mall').classList.toggle('active',t==='all');
  const mpm=document.getElementById('tab-mpm');
  if(mpm) mpm.classList.toggle('active',t==='prune');
  renderModels();
}}

function setWfFilter(f) {{
  wfFilter=f;
  ['all','tb','c','i'].forEach(id=>document.getElementById('fwf-'+id).classList.toggle('active',id===f));
  renderWf();
}}

function setModelFilter(f) {{
  modelFilter=f;
  ['all','nowf','img','missingimg','chat','missingchat','travel','missing'].forEach(id=>{{const el=document.getElementById('fmod-'+id);if(el)el.classList.toggle('active',id===f)}});
  renderModels();
}}

function applySearch() {{
  searchTerm=document.getElementById('globalSearch').value.toLowerCase();
  renderWf(); renderModels();
}}

function handleWfClick(el) {{
  const idx=parseInt(el.dataset.idx);
  const src=getWfSource();
  const filtered=src.filter(wf=>{{
    if(!wfMatchesFilter(wf)) return false;
    if(searchTerm && !wf.name.toLowerCase().includes(searchTerm)) return false;
    return true;
  }});
  if(idx<filtered.length) selectWf(filtered[idx].key, filtered[idx].name||filtered[idx].key);
}}
function handleModelClick(el) {{
  const idx=parseInt(el.dataset.idx);
  const msrc=modelTab==='prune'?PRUNE_M:MODELS;
  const filtered=msrc.filter(m=>{{
    if(!modelMatchesFilter(m)) return false;
    if(searchTerm&&!m.filename.toLowerCase().includes(searchTerm)&&!(m.category||'').toLowerCase().includes(searchTerm)) return false;
    return true;
  }});
  if(idx<filtered.length) selectModel(filtered[idx].key, filtered[idx].filename);
}}
function toggleShowOnlyWf() {{
  showOnlyWf=!showOnlyWf;
  const btn=document.getElementById('toggleWf');
  if(btn) btn.classList.toggle('active',showOnlyWf);
  renderWf();
}}
function toggleShowOnlyModel() {{
  showOnlyModel=!showOnlyModel;
  const btn=document.getElementById('toggleModel');
  if(btn) btn.classList.toggle('active',showOnlyModel);
  renderModels();
}}
function clearSelection() {{
  selectedWf=null; selectedModel=null;
  highlightedModels.clear(); highlightedWfs.clear();
  showOnlyWf=false; showOnlyModel=false;
  const twf=document.getElementById('toggleWf'); if(twf) twf.classList.remove('active');
  const tmod=document.getElementById('toggleModel'); if(tmod) tmod.classList.remove('active');
  renderWf(); renderModels();
  document.getElementById('wf-info').textContent='Click a workflow to see its models';
  document.getElementById('model-info').textContent='Click a model to see its workflows';
}}

function getWfSource() {{
  if(wfTab==='si') return SI_WF;
  if(wfTab==='yr') return YR_WF;
  if(wfTab==='older') return OLDER_WF;
  if(wfTab==='pwf') return PRUNE_WF;
  return ALL_WF;
}}

function wfMatchesFilter(wf) {{
  if(wfFilter==='all') return true;
  const n=wf.name.toLowerCase();
  if(wfFilter==='tb') return /[(]tb[)]/.test(n);
  if(wfFilter==='c') return /[(]c[)]/.test(n) && !/[(]tb[)]/.test(n);
  if(wfFilter==='i') return /[(]i[)]/.test(n);
  return true;
}}

function modelMatchesFilter(m) {{
  if(modelFilter==='all') return true;
  const oh=m.on_hosts;
  if(modelFilter==='nowf') return (m.wf_count||0)===0;
  if(modelFilter==='img') return oh.IMAGEBEAST;
  if(modelFilter==='missingimg') return !oh.IMAGEBEAST && (oh.CHATWORKHORSE||oh.TRAVELBEAST);
  if(modelFilter==='chat') return oh.CHATWORKHORSE;
  if(modelFilter==='missingchat') return oh.IMAGEBEAST && !oh.CHATWORKHORSE;
  if(modelFilter==='travel') return oh.TRAVELBEAST;
  if(modelFilter==='missing') return oh.IMAGEBEAST && !oh.TRAVELBEAST;
  return true;
}}

function hostDots(hs, isModel) {{
  return HN.map(h=>{{
    const cls=isModel?(hs[h]?'dot dot-on':'dot dot-off'):'dot dot-'+(hs[h]||'N');
    return '<span class="'+cls+'" title="'+HS[h]+'"></span>';
  }}).join('');
}}

function renderWf() {{
  const container=document.getElementById('wf-list');
  const src=getWfSource();
  const filtered=src.filter(wf=>{{
    if(!wfMatchesFilter(wf)) return false;
    if(searchTerm && !wf.name.toLowerCase().includes(searchTerm)) return false;
    return true;
  }});
  document.getElementById('cnt-si').textContent='('+SI_WF.length+')';
  document.getElementById('cnt-yr').textContent='('+YR_WF.length+')';
  document.getElementById('cnt-all').textContent='('+ALL_WF.length+')';
  const colder=document.getElementById('cnt-older');
  if(colder) colder.textContent='('+OLDER_WF.length+')';
  const cpwf=document.getElementById('cnt-pwf');
  if(cpwf) cpwf.textContent='('+PRUNE_WF.length+')';

  if(!filtered.length){{container.innerHTML='<div class="empty">No workflows match</div>';return;}}
  const hasSel=highlightedWfs.size>0;
  const visibleWf=showOnlyWf&&hasSel?filtered.filter(wf=>highlightedWfs.has(wf.name||wf.key)||selectedWf===wf.key):filtered;
  const wfFiltered=visibleWf; container.innerHTML=visibleWf.map((wf,i)=>{{
    const isSel=selectedWf===wf.key;
    const isHi=highlightedWfs.has(wf.name||wf.key);
    const isDim=hasSel&&!isHi&&!isSel&&!showOnlyWf;
    let cls='item'+(isSel?' selected':isHi?' highlighted':isDim?' dimmed':'');
    const dots=wf.hs?'<div class="host-dots">'+hostDots(wf.hs,false)+'</div>':'';
    const mcount=wf.models?'<span class="item-meta">'+wf.models.length+'m</span>':'';
    const meta=wf.modified?'<span class="item-meta">'+wf.modified+'</span>':'';
    const prune=wfTab==='pwf'&&wf.reason?'<span class="prune-reason">'+wf.reason+'</span>':'';
    return '<div class="'+cls+'" data-idx="'+i+'" onclick="handleWfClick(this)">'
      +dots+'<span class="item-name" title="'+wf.name+'">'+wf.name+'</span>'+mcount+meta+prune+'</div>';
  }}).join('');
}}

function renderModels() {{
  const container=document.getElementById('model-list');
  const src=modelTab==='prune'?PRUNE_M:MODELS;
  const filtered=src.filter(m=>{{
    if(!modelMatchesFilter(m)) return false;
    if(searchTerm&&!m.filename.toLowerCase().includes(searchTerm)&&!(m.category||'').toLowerCase().includes(searchTerm)) return false;
    return true;
  }});
  document.getElementById('cnt-mall').textContent='('+MODELS.length+')';
  const cmpm=document.getElementById('cnt-mpm');
  if(cmpm) cmpm.textContent='('+PRUNE_M.length+')';

  if(!filtered.length){{container.innerHTML='<div class="empty">No models match</div>';return;}}
  const hasSel=highlightedModels.size>0;
  const visibleMod=showOnlyModel&&hasSel?filtered.filter(m=>highlightedModels.has(m.key)||selectedModel===m.key):filtered;
  const modFiltered=visibleMod; container.innerHTML=visibleMod.map((m,i)=>{{
    const isSel=selectedModel===m.key;
    const isHi=highlightedModels.has(m.key);
    const isDim=hasSel&&!isHi&&!isSel&&!showOnlyModel;
    let cls='item'+(isSel?' selected':isHi?' highlighted':isDim?' dimmed':'');
    const dots='<div class="host-dots">'+hostDots(m.on_hosts,true)+'</div>';
    const size=m.size_gb?'<span class="item-size">'+m.size_gb.toFixed(1)+'GB</span>':'';
    const cat=m.category?'<span class="cat-tag">'+m.category+'</span>':'';
    const wfc='<span class="item-meta">'+(m.wf_count||(m.workflows||[]).length)+'wf</span>';
    const prune=modelTab==='prune'&&m.reason?'<span class="prune-badge">prune</span>':'';
    return '<div class="'+cls+'" data-idx="'+i+'" onclick="handleModelClick(this)">'
      +dots+cat+'<span class="item-name" title="'+m.filename+'">'+m.filename+'</span>'+wfc+size+prune+'</div>';
  }}).join('');
}}

function selectWf(wfKey,wfName) {{
  if(selectedWf===wfKey){{clearSelection();return;}}
  selectedWf=wfKey; selectedModel=null;
  const all=[...SI_WF,...YR_WF,...ALL_WF];
  const wf=all.find(w=>w.key===wfKey);
  if(!wf) return;
  highlightedModels=new Set(wf.models||[]);
  highlightedWfs.clear();
  document.getElementById('wf-info').textContent='"'+wfName+'" — '+(wf.models||[]).length+' model refs';
  document.getElementById('model-info').textContent='Showing models for: '+wfName;
  renderWf(); renderModels();
}}

function selectModel(mk,filename) {{
  if(selectedModel===mk){{clearSelection();return;}}
  selectedModel=mk; selectedWf=null;
  const model=MODELS.find(m=>m.key===mk);
  if(!model) return;
  highlightedWfs=new Set(model.workflows||[]);
  highlightedModels.clear();
  const onCount=Object.values(model.on_hosts).filter(Boolean).length;
  document.getElementById('model-info').textContent='"'+filename+'" — '+onCount+'/'+HN.length+' machines, '+(model.workflows||[]).length+' workflows';
  document.getElementById('wf-info').textContent='Showing workflows using: '+filename;
  renderWf(); renderModels();
}}

renderWf(); renderModels();
"""

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>ComfyUI Fleet Explorer — {timestamp}</title>
<style>{CSS}</style>
</head>
<body>
<div class="header">
  <h1>⚡ Fleet Explorer</h1>
  <span class="ts">{timestamp}</span>
  <input class="search-box" id="globalSearch" placeholder="Search models or workflows..." oninput="applySearch()">
  <button class="mode-btn active" id="normalBtn" onclick="setMode('normal')">Normal</button>
  <button class="mode-btn" id="pruneBtn" onclick="setMode('prune')">🔪 Pruning Mode</button>
  <button class="clear-btn" onclick="clearSelection()">Clear</button>
</div>
<div class="main">
  <div class="panel panel-workflows">
    <div class="panel-header">
      <h2>WORKFLOWS</h2>
      <div class="tabs">
        <button class="tab active" id="tab-si" onclick="switchTab('si')">Starting Images <span id="cnt-si"></span></button>
        <button class="tab" id="tab-yr" onclick="switchTab('yr')">{year_filter} <span id="cnt-yr"></span></button>
        <button class="tab" id="tab-older" onclick="switchTab('older')">Older <span id="cnt-older"></span></button>
        <button class="tab" id="tab-all" onclick="switchTab('all')">All <span id="cnt-all"></span></button>
        <button class="tab" id="tab-pwf" onclick="switchTab('pwf')" style="display:none">🔪 Prune <span id="cnt-pwf"></span></button>
      </div>
    </div>
    <div class="filters">
      <span class="filter-label">Machine:</span>
      <button class="filter-chip active" id="fwf-all" onclick="setWfFilter('all')">All</button>
      <button class="filter-chip" id="fwf-tb" onclick="setWfFilter('tb')">tb</button>
      <button class="filter-chip" id="fwf-c" onclick="setWfFilter('c')">c</button>
      <button class="filter-chip" id="fwf-i" onclick="setWfFilter('i')">i</button>
    </div>
    <div class="list-container" id="wf-list"></div>
    <div class="info-bar" style="display:flex;align-items:center;justify-content:space-between;gap:8px"><span id="wf-info">Click a workflow to see its models</span><button id="toggleWf" class="filter-chip" onclick="toggleShowOnlyWf()">Show Only</button></div>
  </div>
  <div class="panel panel-models">
    <div class="panel-header">
      <h2>MODELS</h2>
      <div class="tabs">
        <button class="tab active" id="tab-mall" onclick="switchModelTab('all')">All <span id="cnt-mall"></span></button>
        <button class="tab" id="tab-mpm" onclick="switchModelTab('prune')" style="display:none">🔪 Prune <span id="cnt-mpm"></span></button>
      </div>
    </div>
    <div class="filters">
      <span class="filter-label">Show:</span>
      <button class="filter-chip active" id="fmod-all" onclick="setModelFilter('all')">All</button>
      <button class="filter-chip" id="fmod-nowf" onclick="setModelFilter('nowf')">No Workflows</button>
      <button class="filter-chip" id="fmod-img" onclick="setModelFilter('img')">On IMG</button>
      <button class="filter-chip" id="fmod-missingimg" onclick="setModelFilter('missingimg')">Missing IMG</button>
      <button class="filter-chip" id="fmod-chat" onclick="setModelFilter('chat')">On Chat</button>
      <button class="filter-chip" id="fmod-missingchat" onclick="setModelFilter('missingchat')">Missing Chat</button>
      <button class="filter-chip" id="fmod-travel" onclick="setModelFilter('travel')">On Travel</button>
      <button class="filter-chip" id="fmod-missing" onclick="setModelFilter('missing')">Missing Travel</button>
    </div>
    <div class="list-container" id="model-list"></div>
    <div class="info-bar" style="display:flex;align-items:center;justify-content:space-between;gap:8px"><span id="model-info">Click a model to see its workflows</span><button id="toggleModel" class="filter-chip" onclick="toggleShowOnlyModel()">Show Only</button></div>
  </div>
</div>
<script>{JS}</script>
</body>
</html>"""

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="ComfyUI Fleet Analysis")
    parser.add_argument("--config", default=None, help="Path to fleet_config.json")
    parser.add_argument("--year",   default=None, help="Override workflow year filter")
    args = parser.parse_args()

    # Find config - check: explicit arg, CWD, then script directory
    if args.config:
        config_path = Path(args.config)
    else:
        cwd_config    = Path.cwd() / "fleet_config.json"
        script_config = Path(__file__).parent / "fleet_config.json"
        if cwd_config.exists():
            config_path = cwd_config
        elif script_config.exists():
            config_path = script_config
        else:
            print("ERROR: fleet_config.json not found.")
            print(f"  Looked in: {Path.cwd()} and {Path(__file__).parent}")
            print("  Pass --config /path/to/fleet_config.json or put fleet_config.json in current directory.")
            sys.exit(1)

    print(f"Loading config: {config_path}")
    config      = load_config(config_path)
    year_filter = args.year or config.get("workflow_year_filter", "2026")
    reports_dir = Path(config["reports_dir"])
    output_dir  = Path(config.get("output_dir", reports_dir / "fleet-output"))
    history_dir = Path(config.get("history_dir", reports_dir / "history"))
    timestamp   = datetime.now().strftime("%Y-%m-%d_%H%M")

    output_dir.mkdir(parents=True, exist_ok=True)
    history_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nReports dir : {reports_dir}")
    print(f"Output dir  : {output_dir}")
    print(f"Year filter : {year_filter}")
    print()

    # Load all machine data
    data = load_all_machines(config)
    if not data:
        print("ERROR: No machine data loaded. Check reports_dir and file patterns.")
        sys.exit(1)

    # Load history for drift detection
    previous = load_history(history_dir)
    drift    = compute_drift(previous, data)
    if previous:
        print(f"\nDrift comparison vs: {previous.get('timestamp','?')}")
    else:
        print("\nNo previous snapshot found — this run will be the baseline.")

    # Build universe
    universe = build_model_universe(data)
    wf_data  = build_workflow_model_data(data, year_filter)

    # Identify source machine
    source_host = next(
        (h for h, m in config["machines"].items() if m.get("is_source")),
        list(data.keys())[0]
    )
    src_models_root = config["sync"]["source_models_root"]
    dest_models_bare = config["sync"]["dest_models_bare"]

    # Readiness per machine
    readiness = {}
    for hostname in data:
        readiness[hostname] = compute_readiness(data, wf_data, hostname, year_filter)

    # Node analysis
    nodes_data = analyze_nodes(data, wf_data)

    # Model gaps
    vram_ok    = config["vram_thresholds"]["ok"]
    vram_maybe = config["vram_thresholds"]["maybe"]

    source_models = data[source_host]["models"] if source_host in data else {}

    # Group non-source machines by sync_group (explicit) or fall back to hostname
    # Machines in the same sync_group share a Models_bare destination
    gaps         = []
    sync_scripts = {}

    dest_groups = defaultdict(list)
    for hostname, machine in data.items():
        if hostname == source_host:
            continue
        group_key = config["machines"][hostname].get("sync_group", hostname)
        dest_groups[group_key].append(hostname)

    for dest_bare, hostnames_in_group in dest_groups.items():
        # Use the lowest VRAM in the group as the constraint
        vram = min(config["machines"][h].get("vram_gb", 99) for h in hostnames_in_group)
        group_label = " + ".join(hostnames_in_group)

        # Union of what ALL machines in this group are missing
        # (if they share Models_bare, missing set is identical, but union is safe)
        missing_keys = set()
        for hostname in hostnames_in_group:
            machine = data[hostname]
            for fn_lower in wf_data:
                if fn_lower not in machine["models"] and fn_lower in source_models:
                    if max_wf_count(wf_data[fn_lower]) >= 3:
                        missing_keys.add(fn_lower)

        missing = []
        for fn_lower in missing_keys:
            sz   = universe.get(fn_lower, {}).get("size_gb", 0)
            cat  = universe.get(fn_lower, {}).get("category", "")
            rel  = source_models[fn_lower].get("relative_path", fn_lower)
            missing.append({
                "filename":       source_models[fn_lower]["filename"],
                "filename_lower": fn_lower,
                "category":       cat,
                "size_gb":        sz,
                "wf_count":       max_wf_count(wf_data[fn_lower]),
                "relative_path":  rel,
            })
        missing.sort(key=lambda x: x["wf_count"], reverse=True)

        ok_models    = [m for m in missing if m["size_gb"] <= vram_ok]
        maybe_models = [m for m in missing if vram_ok < m["size_gb"] <= vram_maybe]
        big_models   = [m for m in missing if m["size_gb"] > vram_maybe]

        # Script name based on group (use first hostname if shared)
        script_tag = hostnames_in_group[0] if len(hostnames_in_group) == 1 else "ModelsBase"

        gaps.append({
            "title":       f"Copy to {group_label} — OK models (<= {vram_ok} GB, safe for {vram}GB VRAM)",
            "models":      ok_models,
            "script_name": f"sync_{script_tag}_MIN.bat",
            "is_sync":     True,
            "priority":    "high",
        })
        gaps.append({
            "title":       f"Copy to {group_label} — MAYBE models ({vram_ok}-{vram_maybe} GB, marginal for {vram}GB VRAM)",
            "models":      maybe_models,
            "script_name": f"sync_{script_tag}_MAYBE.bat",
            "is_sync":     True,
            "priority":    "medium",
        })
        gaps.append({
            "title":       f"Skip for {group_label} — BIG models (> {vram_maybe} GB, too large for {vram}GB VRAM)",
            "models":      big_models,
            "is_sync":     False,
            "priority":    "low",
        })

        if ok_models:
            script = generate_robocopy(
                ok_models,
                f"sync_{script_tag}_MIN  -- Safe for {vram}GB VRAM (<= {vram_ok}GB each)",
                f"Copies to Models_bare shared by: {group_label}",
                src_models_root, dest_models_bare
            )
            sync_scripts[f"sync_{script_tag}_MIN.bat"] = script

        if maybe_models:
            script = generate_robocopy(
                maybe_models,
                f"sync_{script_tag}_MAYBE  -- Marginal ({vram_ok}-{vram_maybe}GB each)",
                f"Run after MIN. Marginal for {vram}GB VRAM — test before travelling.",
                src_models_root, dest_models_bare
            )
            sync_scripts[f"sync_{script_tag}_MAYBE.bat"] = script

    # Subdir mismatch analysis
    subdir_mismatches = analyze_subdir_mismatches(data, config)

    # Prime workflow coverage analysis
    prime_scan     = scan_prime_workflows(config)
    prime_coverage = analyze_prime_coverage(data, prime_scan, config)
    if prime_scan:
        print(f"Current year workflows scanned: {prime_scan['json_count']} JSON, {prime_scan['png_count']} PNG  ({len(prime_scan['prime_models'])} unique model refs)")
    else:
        print("Prime workflows: no prime_workflows_dir configured")

    # Starting Images dedicated coverage (from CSV source=starting_images rows)
    si_scan     = scan_starting_images(data)
    si_coverage = analyze_starting_images_coverage(data, si_scan)
    if si_scan.get("png_count", 0) > 0:
        print(f"Starting Images: {si_scan['png_count']} PNGs, {len(si_scan.get('models', set()))} unique model refs")
    else:
        print("Starting Images: no source=starting_images rows found — re-run fleet scans on Windows machines")

    # Build actions
    report_data = {
        "machines":         data,
        "drift":            drift,
        "readiness":        readiness,
        "nodes":            nodes_data,
        "gaps":             gaps,
        "universe":         universe,
        "actions":          [],
        "subdir_mismatches": subdir_mismatches,
        "prime_coverage":   prime_coverage,
        "prime_scan":       prime_scan,
        "si_coverage":      si_coverage,
        "si_scan":          si_scan,
    }
    report_data["actions"] = build_actions(gaps, readiness, drift, nodes_data)

    # --- Write outputs ---

    # Robocopy scripts
    for name, script in sync_scripts.items():
        out = output_dir / name
        out.write_text(script)
        print(f"Written: {out.name}")

    # Custom nodes text report
    nodes_lines = []
    nodes_lines.append("CUSTOM NODES FLEET COMPARISON")
    nodes_lines.append(f"Generated: {timestamp}")
    nodes_lines.append("=" * 68)
    nodes_lines.append(f"  {'Node':<45} " + "  ".join(f"[{h[:6]}]" for h in nodes_data["hostnames"]))
    nodes_lines.append("-" * 68)
    for node in nodes_data["all_nodes"]:
        row = nodes_data["matrix"][node]
        cols = "     ".join("Y" if row.get(h) else " " for h in nodes_data["hostnames"])
        nodes_lines.append(f"  {node:<45} {cols}")
    nodes_lines.append("")
    nodes_lines.append("ON ALL MACHINES: " + ", ".join(nodes_data["on_all"]))
    (output_dir / f"custom_nodes_{timestamp}.txt").write_text("\n".join(nodes_lines))
    print(f"Written: custom_nodes_{timestamp}.txt")

    # Subdir mismatch report
    if subdir_mismatches:
        mismatch_lines = [
            "SUBDIR MISMATCH REPORT",
            f"Generated: {timestamp}",
            "Models that exist on both ImageBeast and Models_bare but in different subdirectories.",
            "Fix: run fix_subdir_structure.bat to copy to correct location, then delete old.",
            "=" * 72,
            "",
        ]
        for m in subdir_mismatches:
            mismatch_lines.append(f"  {m['filename']}  ({m['size_gb']:.2f} GB)")
            mismatch_lines.append(f"    ImageBeast (correct): {m['src_rel']}")
            mismatch_lines.append(f"    Models_bare (current): {m['dest_rel']}")
            mismatch_lines.append("")
        mismatch_lines.append(f"Total: {len(subdir_mismatches)} mismatches")
        (output_dir / f"subdir_mismatches_{timestamp}.txt").write_text("\n".join(mismatch_lines))
        print(f"Written: subdir_mismatches_{timestamp}.txt")

        fix_bat = generate_subdir_fix_bat(subdir_mismatches, src_models_root, dest_models_bare)
        (output_dir / "fix_subdir_structure.bat").write_text(fix_bat)
        print(f"Written: fix_subdir_structure.bat  ({len(subdir_mismatches)} files to relocate)")
    else:
        print("Subdir structure: OK (no mismatches found)")

    # HTML report
    html = generate_html(report_data, timestamp, year_filter)
    html_path = output_dir / f"fleet_report_{timestamp}.html"
    html_path.write_text(html)
    print(f"Written: fleet_report_{timestamp}.html")

    # Fleet explorer
    explorer_html = generate_explorer_html(data, timestamp, year_filter)
    explorer_path = output_dir / f"fleet_explorer_{timestamp}.html"
    explorer_path.write_text(explorer_html)
    print(f"Written: fleet_explorer_{timestamp}.html")

    # Text summary
    summary_lines = []
    summary_lines.append(f"ComfyUI Fleet Analysis  {timestamp}")
    summary_lines.append(f"Year filter: {year_filter}")
    summary_lines.append("=" * 60)
    summary_lines.append("")
    summary_lines.append("READINESS")
    summary_lines.append("-" * 60)
    for h, r in readiness.items():
        vram = config["machines"][h].get("vram_gb", "?")
        summary_lines.append(f"  {h:<16} {r.get('pct',0):>3}%  ({r.get('can_run',0)}/{r.get('total',0)} workflows)  {vram}GB VRAM")
    summary_lines.append("")
    summary_lines.append("NEXT ACTIONS")
    summary_lines.append("-" * 60)
    for a in report_data["actions"]:
        p = {"high": "!!!", "medium": " ! ", "low": "   "}.get(a["priority"], "   ")
        summary_lines.append(f"  [{p}]  {a['title']}")
        summary_lines.append(f"         {a['detail']}")
    if prime_coverage and prime_scan:
        summary_lines.append("")
        summary_lines.append(f"CURRENT YEAR WORKFLOW COVERAGE ({year_filter})")
        summary_lines.append("-" * 60)
        total_prime = len(prime_scan.get("prime_models", set()))
        summary_lines.append(f"  Prime models referenced: {total_prime}")
        for hostname, cov in prime_coverage.items():
            confirmed = cov["confirmed"]
            missing   = cov["missing"]
            beyond    = cov["beyond"]
            total_beyond_gb = sum(b["size_gb"] for b in beyond)
            summary_lines.append(f"  {hostname}:")
            summary_lines.append(f"    Confirmed: {len(confirmed)}  Missing: {len(missing)}  Beyond: {len(beyond)} ({total_beyond_gb:.2f} GB)")
            for m in missing:
                summary_lines.append(f"    !! MISSING: {m}")

    if si_coverage and si_scan and si_scan.get("png_count", 0) > 0:
        summary_lines.append("")
        summary_lines.append("STARTING IMAGES — TRAVEL READINESS")
        summary_lines.append("-" * 60)
        summary_lines.append(f"  {si_scan['png_count']} PNGs scanned | {len(si_scan.get('models', set()))} model refs")
        for hostname, cov in si_coverage.items():
            confirmed = cov["confirmed"]
            missing   = cov["missing"]
            beyond    = cov["beyond"]
            total_beyond_gb = sum(b["size_gb"] for b in beyond)
            status = "READY" if not missing else "NOT READY"
            summary_lines.append(f"  {hostname}: {status}  ({len(confirmed)} present, {len(missing)} missing, {len(beyond)} beyond/{total_beyond_gb:.2f}GB)")
            for m in missing:
                summary_lines.append(f"    !! MISSING: {m}")

    if subdir_mismatches:
        summary_lines.append("")
        summary_lines.append("SUBDIR MISMATCHES")
        summary_lines.append("-" * 60)
        summary_lines.append(f"  {len(subdir_mismatches)} models in wrong subdir — run fix_subdir_structure.bat")
        for m in subdir_mismatches[:10]:
            summary_lines.append(f"  {m['filename']}")
            summary_lines.append(f"    is  : {m['dest_rel']}")
            summary_lines.append(f"    want: {m['src_rel']}")
        if len(subdir_mismatches) > 10:
            summary_lines.append(f"  ... and {len(subdir_mismatches)-10} more (see subdir_mismatches_*.txt)")
    else:
        summary_lines.append("")
        summary_lines.append("SUBDIR STRUCTURE: OK")
    (output_dir / f"summary_{timestamp}.txt").write_text("\n".join(summary_lines))
    print(f"Written: summary_{timestamp}.txt")

    # Save snapshot for next run's drift detection
    save_snapshot(history_dir, data, timestamp)

    # Print summary to console
    print()
    print("\n".join(summary_lines))
    print(f"\nAll outputs in: {output_dir}")


if __name__ == "__main__":
    main()
